// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetWorkflowByIDHandlerFunc turns a function with the right signature into a get workflow by Id handler
type GetWorkflowByIDHandlerFunc func(GetWorkflowByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetWorkflowByIDHandlerFunc) Handle(params GetWorkflowByIDParams) middleware.Responder {
	return fn(params)
}

// GetWorkflowByIDHandler interface for that can handle valid get workflow by Id params
type GetWorkflowByIDHandler interface {
	Handle(GetWorkflowByIDParams) middleware.Responder
}

// NewGetWorkflowByID creates a new http.Handler for the get workflow by Id operation
func NewGetWorkflowByID(ctx *middleware.Context, handler GetWorkflowByIDHandler) *GetWorkflowByID {
	return &GetWorkflowByID{Context: ctx, Handler: handler}
}

/*GetWorkflowByID swagger:route GET /api/v1.0/workflows/{workflow-id} getWorkflowById

Returns the '/workflows/{workflow-id}'

*/
type GetWorkflowByID struct {
	Context *middleware.Context
	Handler GetWorkflowByIDHandler
}

func (o *GetWorkflowByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetWorkflowByIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
