// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetVersionsOKCode is the HTTP code returned for type GetVersionsOK
const GetVersionsOKCode int = 200

/*GetVersionsOK Response of getting Shipyard versions

swagger:response getVersionsOK
*/
type GetVersionsOK struct {

	/*
	  In: Body
	*/
	Payload *GetVersionsOKBody `json:"body,omitempty"`
}

// NewGetVersionsOK creates GetVersionsOK with default headers values
func NewGetVersionsOK() *GetVersionsOK {

	return &GetVersionsOK{}
}

// WithPayload adds the payload to the get versions o k response
func (o *GetVersionsOK) WithPayload(payload *GetVersionsOKBody) *GetVersionsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get versions o k response
func (o *GetVersionsOK) SetPayload(payload *GetVersionsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetVersionsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
