// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetWFActionStepByIDHandlerFunc turns a function with the right signature into a get w f action step by Id handler
type GetWFActionStepByIDHandlerFunc func(GetWFActionStepByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetWFActionStepByIDHandlerFunc) Handle(params GetWFActionStepByIDParams) middleware.Responder {
	return fn(params)
}

// GetWFActionStepByIDHandler interface for that can handle valid get w f action step by Id params
type GetWFActionStepByIDHandler interface {
	Handle(GetWFActionStepByIDParams) middleware.Responder
}

// NewGetWFActionStepByID creates a new http.Handler for the get w f action step by Id operation
func NewGetWFActionStepByID(ctx *middleware.Context, handler GetWFActionStepByIDHandler) *GetWFActionStepByID {
	return &GetWFActionStepByID{Context: ctx, Handler: handler}
}

/*GetWFActionStepByID swagger:route GET /api/v1.0/actions/{action-id}/steps/{step-id} getWFActionStepById

Retrieve an action step by its id

*/
type GetWFActionStepByID struct {
	Context *middleware.Context
	Handler GetWFActionStepByIDHandler
}

func (o *GetWFActionStepByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetWFActionStepByIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
