// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetActionByActionIDOKCode is the HTTP code returned for type GetActionByActionIDOK
const GetActionByActionIDOKCode int = 200

/*GetActionByActionIDOK Generic String answer

swagger:response getActionByActionIdOK
*/
type GetActionByActionIDOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetActionByActionIDOK creates GetActionByActionIDOK with default headers values
func NewGetActionByActionIDOK() *GetActionByActionIDOK {

	return &GetActionByActionIDOK{}
}

// WithPayload adds the payload to the get action by action Id o k response
func (o *GetActionByActionIDOK) WithPayload(payload string) *GetActionByActionIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get action by action Id o k response
func (o *GetActionByActionIDOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetActionByActionIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetActionByActionIDUnauthorizedCode is the HTTP code returned for type GetActionByActionIDUnauthorized
const GetActionByActionIDUnauthorizedCode int = 401

/*GetActionByActionIDUnauthorized 401 Not authorized

swagger:response getActionByActionIdUnauthorized
*/
type GetActionByActionIDUnauthorized struct {
}

// NewGetActionByActionIDUnauthorized creates GetActionByActionIDUnauthorized with default headers values
func NewGetActionByActionIDUnauthorized() *GetActionByActionIDUnauthorized {

	return &GetActionByActionIDUnauthorized{}
}

// WriteResponse to the client
func (o *GetActionByActionIDUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetActionByActionIDForbiddenCode is the HTTP code returned for type GetActionByActionIDForbidden
const GetActionByActionIDForbiddenCode int = 403

/*GetActionByActionIDForbidden 403 Forbidden

swagger:response getActionByActionIdForbidden
*/
type GetActionByActionIDForbidden struct {
}

// NewGetActionByActionIDForbidden creates GetActionByActionIDForbidden with default headers values
func NewGetActionByActionIDForbidden() *GetActionByActionIDForbidden {

	return &GetActionByActionIDForbidden{}
}

// WriteResponse to the client
func (o *GetActionByActionIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// GetActionByActionIDInternalServerErrorCode is the HTTP code returned for type GetActionByActionIDInternalServerError
const GetActionByActionIDInternalServerErrorCode int = 500

/*GetActionByActionIDInternalServerError 500 Internal Server Error

swagger:response getActionByActionIdInternalServerError
*/
type GetActionByActionIDInternalServerError struct {
}

// NewGetActionByActionIDInternalServerError creates GetActionByActionIDInternalServerError with default headers values
func NewGetActionByActionIDInternalServerError() *GetActionByActionIDInternalServerError {

	return &GetActionByActionIDInternalServerError{}
}

// WriteResponse to the client
func (o *GetActionByActionIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
