// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetActionByActionIDHandlerFunc turns a function with the right signature into a get action by action Id handler
type GetActionByActionIDHandlerFunc func(GetActionByActionIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetActionByActionIDHandlerFunc) Handle(params GetActionByActionIDParams) middleware.Responder {
	return fn(params)
}

// GetActionByActionIDHandler interface for that can handle valid get action by action Id params
type GetActionByActionIDHandler interface {
	Handle(GetActionByActionIDParams) middleware.Responder
}

// NewGetActionByActionID creates a new http.Handler for the get action by action Id operation
func NewGetActionByActionID(ctx *middleware.Context, handler GetActionByActionIDHandler) *GetActionByActionID {
	return &GetActionByActionID{Context: ctx, Handler: handler}
}

/*GetActionByActionID swagger:route GET /api/v1.0/actions/{action-id} getActionByActionId

Returns the '/actions/{action-id}'

*/
type GetActionByActionID struct {
	Context *middleware.Context
	Handler GetActionByActionIDHandler
}

func (o *GetActionByActionID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetActionByActionIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
