// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetRenderedConfigDocsOKCode is the HTTP code returned for type GetRenderedConfigDocsOK
const GetRenderedConfigDocsOKCode int = 200

/*GetRenderedConfigDocsOK Generic String answer

swagger:response getRenderedConfigDocsOK
*/
type GetRenderedConfigDocsOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetRenderedConfigDocsOK creates GetRenderedConfigDocsOK with default headers values
func NewGetRenderedConfigDocsOK() *GetRenderedConfigDocsOK {

	return &GetRenderedConfigDocsOK{}
}

// WithPayload adds the payload to the get rendered config docs o k response
func (o *GetRenderedConfigDocsOK) WithPayload(payload string) *GetRenderedConfigDocsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get rendered config docs o k response
func (o *GetRenderedConfigDocsOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRenderedConfigDocsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetRenderedConfigDocsUnauthorizedCode is the HTTP code returned for type GetRenderedConfigDocsUnauthorized
const GetRenderedConfigDocsUnauthorizedCode int = 401

/*GetRenderedConfigDocsUnauthorized 401 Not authorized

swagger:response getRenderedConfigDocsUnauthorized
*/
type GetRenderedConfigDocsUnauthorized struct {
}

// NewGetRenderedConfigDocsUnauthorized creates GetRenderedConfigDocsUnauthorized with default headers values
func NewGetRenderedConfigDocsUnauthorized() *GetRenderedConfigDocsUnauthorized {

	return &GetRenderedConfigDocsUnauthorized{}
}

// WriteResponse to the client
func (o *GetRenderedConfigDocsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetRenderedConfigDocsForbiddenCode is the HTTP code returned for type GetRenderedConfigDocsForbidden
const GetRenderedConfigDocsForbiddenCode int = 403

/*GetRenderedConfigDocsForbidden 403 Forbidden

swagger:response getRenderedConfigDocsForbidden
*/
type GetRenderedConfigDocsForbidden struct {
}

// NewGetRenderedConfigDocsForbidden creates GetRenderedConfigDocsForbidden with default headers values
func NewGetRenderedConfigDocsForbidden() *GetRenderedConfigDocsForbidden {

	return &GetRenderedConfigDocsForbidden{}
}

// WriteResponse to the client
func (o *GetRenderedConfigDocsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// GetRenderedConfigDocsInternalServerErrorCode is the HTTP code returned for type GetRenderedConfigDocsInternalServerError
const GetRenderedConfigDocsInternalServerErrorCode int = 500

/*GetRenderedConfigDocsInternalServerError 500 Internal Server Error

swagger:response getRenderedConfigDocsInternalServerError
*/
type GetRenderedConfigDocsInternalServerError struct {
}

// NewGetRenderedConfigDocsInternalServerError creates GetRenderedConfigDocsInternalServerError with default headers values
func NewGetRenderedConfigDocsInternalServerError() *GetRenderedConfigDocsInternalServerError {

	return &GetRenderedConfigDocsInternalServerError{}
}

// WriteResponse to the client
func (o *GetRenderedConfigDocsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
