// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetRenderedConfigDocsHandlerFunc turns a function with the right signature into a get rendered config docs handler
type GetRenderedConfigDocsHandlerFunc func(GetRenderedConfigDocsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetRenderedConfigDocsHandlerFunc) Handle(params GetRenderedConfigDocsParams) middleware.Responder {
	return fn(params)
}

// GetRenderedConfigDocsHandler interface for that can handle valid get rendered config docs params
type GetRenderedConfigDocsHandler interface {
	Handle(GetRenderedConfigDocsParams) middleware.Responder
}

// NewGetRenderedConfigDocs creates a new http.Handler for the get rendered config docs operation
func NewGetRenderedConfigDocs(ctx *middleware.Context, handler GetRenderedConfigDocsHandler) *GetRenderedConfigDocs {
	return &GetRenderedConfigDocs{Context: ctx, Handler: handler}
}

/*GetRenderedConfigDocs swagger:route GET /api/v1.0/renderedconfigdocs getRenderedConfigDocs

Returns the '/renderedconfigdocs'

*/
type GetRenderedConfigDocs struct {
	Context *middleware.Context
	Handler GetRenderedConfigDocsHandler
}

func (o *GetRenderedConfigDocs) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetRenderedConfigDocsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
