// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetWFActionByIDOKCode is the HTTP code returned for type GetWFActionByIDOK
const GetWFActionByIDOKCode int = 200

/*GetWFActionByIDOK Generic String answer

swagger:response getWFActionByIdOK
*/
type GetWFActionByIDOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetWFActionByIDOK creates GetWFActionByIDOK with default headers values
func NewGetWFActionByIDOK() *GetWFActionByIDOK {

	return &GetWFActionByIDOK{}
}

// WithPayload adds the payload to the get w f action by Id o k response
func (o *GetWFActionByIDOK) WithPayload(payload string) *GetWFActionByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get w f action by Id o k response
func (o *GetWFActionByIDOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetWFActionByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetWFActionByIDUnauthorizedCode is the HTTP code returned for type GetWFActionByIDUnauthorized
const GetWFActionByIDUnauthorizedCode int = 401

/*GetWFActionByIDUnauthorized 401 Not authorized

swagger:response getWFActionByIdUnauthorized
*/
type GetWFActionByIDUnauthorized struct {
}

// NewGetWFActionByIDUnauthorized creates GetWFActionByIDUnauthorized with default headers values
func NewGetWFActionByIDUnauthorized() *GetWFActionByIDUnauthorized {

	return &GetWFActionByIDUnauthorized{}
}

// WriteResponse to the client
func (o *GetWFActionByIDUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetWFActionByIDForbiddenCode is the HTTP code returned for type GetWFActionByIDForbidden
const GetWFActionByIDForbiddenCode int = 403

/*GetWFActionByIDForbidden 403 Forbidden

swagger:response getWFActionByIdForbidden
*/
type GetWFActionByIDForbidden struct {
}

// NewGetWFActionByIDForbidden creates GetWFActionByIDForbidden with default headers values
func NewGetWFActionByIDForbidden() *GetWFActionByIDForbidden {

	return &GetWFActionByIDForbidden{}
}

// WriteResponse to the client
func (o *GetWFActionByIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// GetWFActionByIDInternalServerErrorCode is the HTTP code returned for type GetWFActionByIDInternalServerError
const GetWFActionByIDInternalServerErrorCode int = 500

/*GetWFActionByIDInternalServerError 500 Internal Server Error

swagger:response getWFActionByIdInternalServerError
*/
type GetWFActionByIDInternalServerError struct {
}

// NewGetWFActionByIDInternalServerError creates GetWFActionByIDInternalServerError with default headers values
func NewGetWFActionByIDInternalServerError() *GetWFActionByIDInternalServerError {

	return &GetWFActionByIDInternalServerError{}
}

// WriteResponse to the client
func (o *GetWFActionByIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
