// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetNoteDetailsOKCode is the HTTP code returned for type GetNoteDetailsOK
const GetNoteDetailsOKCode int = 200

/*GetNoteDetailsOK Generic String answer

swagger:response getNoteDetailsOK
*/
type GetNoteDetailsOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetNoteDetailsOK creates GetNoteDetailsOK with default headers values
func NewGetNoteDetailsOK() *GetNoteDetailsOK {

	return &GetNoteDetailsOK{}
}

// WithPayload adds the payload to the get note details o k response
func (o *GetNoteDetailsOK) WithPayload(payload string) *GetNoteDetailsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get note details o k response
func (o *GetNoteDetailsOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetNoteDetailsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetNoteDetailsUnauthorizedCode is the HTTP code returned for type GetNoteDetailsUnauthorized
const GetNoteDetailsUnauthorizedCode int = 401

/*GetNoteDetailsUnauthorized 401 Not authorized

swagger:response getNoteDetailsUnauthorized
*/
type GetNoteDetailsUnauthorized struct {
}

// NewGetNoteDetailsUnauthorized creates GetNoteDetailsUnauthorized with default headers values
func NewGetNoteDetailsUnauthorized() *GetNoteDetailsUnauthorized {

	return &GetNoteDetailsUnauthorized{}
}

// WriteResponse to the client
func (o *GetNoteDetailsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetNoteDetailsForbiddenCode is the HTTP code returned for type GetNoteDetailsForbidden
const GetNoteDetailsForbiddenCode int = 403

/*GetNoteDetailsForbidden 403 Forbidden

swagger:response getNoteDetailsForbidden
*/
type GetNoteDetailsForbidden struct {
}

// NewGetNoteDetailsForbidden creates GetNoteDetailsForbidden with default headers values
func NewGetNoteDetailsForbidden() *GetNoteDetailsForbidden {

	return &GetNoteDetailsForbidden{}
}

// WriteResponse to the client
func (o *GetNoteDetailsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// GetNoteDetailsInternalServerErrorCode is the HTTP code returned for type GetNoteDetailsInternalServerError
const GetNoteDetailsInternalServerErrorCode int = 500

/*GetNoteDetailsInternalServerError 500 Internal Server Error

swagger:response getNoteDetailsInternalServerError
*/
type GetNoteDetailsInternalServerError struct {
}

// NewGetNoteDetailsInternalServerError creates GetNoteDetailsInternalServerError with default headers values
func NewGetNoteDetailsInternalServerError() *GetNoteDetailsInternalServerError {

	return &GetNoteDetailsInternalServerError{}
}

// WriteResponse to the client
func (o *GetNoteDetailsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
