// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetActionStepByIDHandlerFunc turns a function with the right signature into a get action step by Id handler
type GetActionStepByIDHandlerFunc func(GetActionStepByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetActionStepByIDHandlerFunc) Handle(params GetActionStepByIDParams) middleware.Responder {
	return fn(params)
}

// GetActionStepByIDHandler interface for that can handle valid get action step by Id params
type GetActionStepByIDHandler interface {
	Handle(GetActionStepByIDParams) middleware.Responder
}

// NewGetActionStepByID creates a new http.Handler for the get action step by Id operation
func NewGetActionStepByID(ctx *middleware.Context, handler GetActionStepByIDHandler) *GetActionStepByID {
	return &GetActionStepByID{Context: ctx, Handler: handler}
}

/*GetActionStepByID swagger:route GET /api/v1.0/actions/{action-id}/steps/{step-id} getActionStepById

Returns the '/actions/{action-id}/steps/{step-id}'

*/
type GetActionStepByID struct {
	Context *middleware.Context
	Handler GetActionStepByIDHandler
}

func (o *GetActionStepByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetActionStepByIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
