// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	errors "github.com/go-openapi/errors"
	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"

	models "github.com/kubekit99/airship-go-api/shipyard/models"
)

// PostApplyManifestHandlerFunc turns a function with the right signature into a post apply manifest handler
type PostApplyManifestHandlerFunc func(PostApplyManifestParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostApplyManifestHandlerFunc) Handle(params PostApplyManifestParams) middleware.Responder {
	return fn(params)
}

// PostApplyManifestHandler interface for that can handle valid post apply manifest params
type PostApplyManifestHandler interface {
	Handle(PostApplyManifestParams) middleware.Responder
}

// NewPostApplyManifest creates a new http.Handler for the post apply manifest operation
func NewPostApplyManifest(ctx *middleware.Context, handler PostApplyManifestHandler) *PostApplyManifest {
	return &PostApplyManifest{Context: ctx, Handler: handler}
}

/*PostApplyManifest swagger:route POST /api/v1.0/apply postApplyManifest

Install or upgrade using an Shipyard manifest

*/
type PostApplyManifest struct {
	Context *middleware.Context
	Handler PostApplyManifestHandler
}

func (o *PostApplyManifest) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostApplyManifestParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostApplyManifestBody post apply manifest body
// swagger:model PostApplyManifestBody
type PostApplyManifestBody struct {

	// JSON or YAML representation of the manifest being processed.
	Hrefs interface{} `json:"hrefs,omitempty"`

	// Set of overrides
	Overrides interface{} `json:"overrides,omitempty"`
}

// Validate validates this post apply manifest body
func (o *PostApplyManifestBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostApplyManifestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostApplyManifestBody) UnmarshalBinary(b []byte) error {
	var res PostApplyManifestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// PostApplyManifestOKBody post apply manifest o k body
// swagger:model PostApplyManifestOKBody
type PostApplyManifestOKBody struct {
	models.Applyresult
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *PostApplyManifestOKBody) UnmarshalJSON(raw []byte) error {
	// PostApplyManifestOKBodyAO0
	var postApplyManifestOKBodyAO0 models.Applyresult
	if err := swag.ReadJSON(raw, &postApplyManifestOKBodyAO0); err != nil {
		return err
	}
	o.Applyresult = postApplyManifestOKBodyAO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o PostApplyManifestOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	postApplyManifestOKBodyAO0, err := swag.WriteJSON(o.Applyresult)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, postApplyManifestOKBodyAO0)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this post apply manifest o k body
func (o *PostApplyManifestOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Applyresult
	if err := o.Applyresult.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (o *PostApplyManifestOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostApplyManifestOKBody) UnmarshalBinary(b []byte) error {
	var res PostApplyManifestOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
