// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// RetrieveConfigDocsClearTextByCollectionIDOKCode is the HTTP code returned for type RetrieveConfigDocsClearTextByCollectionIDOK
const RetrieveConfigDocsClearTextByCollectionIDOKCode int = 200

/*RetrieveConfigDocsClearTextByCollectionIDOK Generic String answer

swagger:response retrieveConfigDocsClearTextByCollectionIdOK
*/
type RetrieveConfigDocsClearTextByCollectionIDOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewRetrieveConfigDocsClearTextByCollectionIDOK creates RetrieveConfigDocsClearTextByCollectionIDOK with default headers values
func NewRetrieveConfigDocsClearTextByCollectionIDOK() *RetrieveConfigDocsClearTextByCollectionIDOK {

	return &RetrieveConfigDocsClearTextByCollectionIDOK{}
}

// WithPayload adds the payload to the retrieve config docs clear text by collection Id o k response
func (o *RetrieveConfigDocsClearTextByCollectionIDOK) WithPayload(payload string) *RetrieveConfigDocsClearTextByCollectionIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the retrieve config docs clear text by collection Id o k response
func (o *RetrieveConfigDocsClearTextByCollectionIDOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RetrieveConfigDocsClearTextByCollectionIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// RetrieveConfigDocsClearTextByCollectionIDUnauthorizedCode is the HTTP code returned for type RetrieveConfigDocsClearTextByCollectionIDUnauthorized
const RetrieveConfigDocsClearTextByCollectionIDUnauthorizedCode int = 401

/*RetrieveConfigDocsClearTextByCollectionIDUnauthorized 401 Not authorized

swagger:response retrieveConfigDocsClearTextByCollectionIdUnauthorized
*/
type RetrieveConfigDocsClearTextByCollectionIDUnauthorized struct {
}

// NewRetrieveConfigDocsClearTextByCollectionIDUnauthorized creates RetrieveConfigDocsClearTextByCollectionIDUnauthorized with default headers values
func NewRetrieveConfigDocsClearTextByCollectionIDUnauthorized() *RetrieveConfigDocsClearTextByCollectionIDUnauthorized {

	return &RetrieveConfigDocsClearTextByCollectionIDUnauthorized{}
}

// WriteResponse to the client
func (o *RetrieveConfigDocsClearTextByCollectionIDUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// RetrieveConfigDocsClearTextByCollectionIDForbiddenCode is the HTTP code returned for type RetrieveConfigDocsClearTextByCollectionIDForbidden
const RetrieveConfigDocsClearTextByCollectionIDForbiddenCode int = 403

/*RetrieveConfigDocsClearTextByCollectionIDForbidden 403 Forbidden

swagger:response retrieveConfigDocsClearTextByCollectionIdForbidden
*/
type RetrieveConfigDocsClearTextByCollectionIDForbidden struct {
}

// NewRetrieveConfigDocsClearTextByCollectionIDForbidden creates RetrieveConfigDocsClearTextByCollectionIDForbidden with default headers values
func NewRetrieveConfigDocsClearTextByCollectionIDForbidden() *RetrieveConfigDocsClearTextByCollectionIDForbidden {

	return &RetrieveConfigDocsClearTextByCollectionIDForbidden{}
}

// WriteResponse to the client
func (o *RetrieveConfigDocsClearTextByCollectionIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// RetrieveConfigDocsClearTextByCollectionIDInternalServerErrorCode is the HTTP code returned for type RetrieveConfigDocsClearTextByCollectionIDInternalServerError
const RetrieveConfigDocsClearTextByCollectionIDInternalServerErrorCode int = 500

/*RetrieveConfigDocsClearTextByCollectionIDInternalServerError 500 Internal Server Error

swagger:response retrieveConfigDocsClearTextByCollectionIdInternalServerError
*/
type RetrieveConfigDocsClearTextByCollectionIDInternalServerError struct {
}

// NewRetrieveConfigDocsClearTextByCollectionIDInternalServerError creates RetrieveConfigDocsClearTextByCollectionIDInternalServerError with default headers values
func NewRetrieveConfigDocsClearTextByCollectionIDInternalServerError() *RetrieveConfigDocsClearTextByCollectionIDInternalServerError {

	return &RetrieveConfigDocsClearTextByCollectionIDInternalServerError{}
}

// WriteResponse to the client
func (o *RetrieveConfigDocsClearTextByCollectionIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
