// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// RetrieveRenderedCleartextConfigDocsOKCode is the HTTP code returned for type RetrieveRenderedCleartextConfigDocsOK
const RetrieveRenderedCleartextConfigDocsOKCode int = 200

/*RetrieveRenderedCleartextConfigDocsOK Generic String answer

swagger:response retrieveRenderedCleartextConfigDocsOK
*/
type RetrieveRenderedCleartextConfigDocsOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewRetrieveRenderedCleartextConfigDocsOK creates RetrieveRenderedCleartextConfigDocsOK with default headers values
func NewRetrieveRenderedCleartextConfigDocsOK() *RetrieveRenderedCleartextConfigDocsOK {

	return &RetrieveRenderedCleartextConfigDocsOK{}
}

// WithPayload adds the payload to the retrieve rendered cleartext config docs o k response
func (o *RetrieveRenderedCleartextConfigDocsOK) WithPayload(payload string) *RetrieveRenderedCleartextConfigDocsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the retrieve rendered cleartext config docs o k response
func (o *RetrieveRenderedCleartextConfigDocsOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RetrieveRenderedCleartextConfigDocsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// RetrieveRenderedCleartextConfigDocsUnauthorizedCode is the HTTP code returned for type RetrieveRenderedCleartextConfigDocsUnauthorized
const RetrieveRenderedCleartextConfigDocsUnauthorizedCode int = 401

/*RetrieveRenderedCleartextConfigDocsUnauthorized 401 Not authorized

swagger:response retrieveRenderedCleartextConfigDocsUnauthorized
*/
type RetrieveRenderedCleartextConfigDocsUnauthorized struct {
}

// NewRetrieveRenderedCleartextConfigDocsUnauthorized creates RetrieveRenderedCleartextConfigDocsUnauthorized with default headers values
func NewRetrieveRenderedCleartextConfigDocsUnauthorized() *RetrieveRenderedCleartextConfigDocsUnauthorized {

	return &RetrieveRenderedCleartextConfigDocsUnauthorized{}
}

// WriteResponse to the client
func (o *RetrieveRenderedCleartextConfigDocsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// RetrieveRenderedCleartextConfigDocsForbiddenCode is the HTTP code returned for type RetrieveRenderedCleartextConfigDocsForbidden
const RetrieveRenderedCleartextConfigDocsForbiddenCode int = 403

/*RetrieveRenderedCleartextConfigDocsForbidden 403 Forbidden

swagger:response retrieveRenderedCleartextConfigDocsForbidden
*/
type RetrieveRenderedCleartextConfigDocsForbidden struct {
}

// NewRetrieveRenderedCleartextConfigDocsForbidden creates RetrieveRenderedCleartextConfigDocsForbidden with default headers values
func NewRetrieveRenderedCleartextConfigDocsForbidden() *RetrieveRenderedCleartextConfigDocsForbidden {

	return &RetrieveRenderedCleartextConfigDocsForbidden{}
}

// WriteResponse to the client
func (o *RetrieveRenderedCleartextConfigDocsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// RetrieveRenderedCleartextConfigDocsInternalServerErrorCode is the HTTP code returned for type RetrieveRenderedCleartextConfigDocsInternalServerError
const RetrieveRenderedCleartextConfigDocsInternalServerErrorCode int = 500

/*RetrieveRenderedCleartextConfigDocsInternalServerError 500 Internal Server Error

swagger:response retrieveRenderedCleartextConfigDocsInternalServerError
*/
type RetrieveRenderedCleartextConfigDocsInternalServerError struct {
}

// NewRetrieveRenderedCleartextConfigDocsInternalServerError creates RetrieveRenderedCleartextConfigDocsInternalServerError with default headers values
func NewRetrieveRenderedCleartextConfigDocsInternalServerError() *RetrieveRenderedCleartextConfigDocsInternalServerError {

	return &RetrieveRenderedCleartextConfigDocsInternalServerError{}
}

// WriteResponse to the client
func (o *RetrieveRenderedCleartextConfigDocsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
