// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteRevisionTagByIDParams creates a new DeleteRevisionTagByIDParams object
// with the default values initialized.
func NewDeleteRevisionTagByIDParams() *DeleteRevisionTagByIDParams {
	var ()
	return &DeleteRevisionTagByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteRevisionTagByIDParamsWithTimeout creates a new DeleteRevisionTagByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteRevisionTagByIDParamsWithTimeout(timeout time.Duration) *DeleteRevisionTagByIDParams {
	var ()
	return &DeleteRevisionTagByIDParams{

		timeout: timeout,
	}
}

// NewDeleteRevisionTagByIDParamsWithContext creates a new DeleteRevisionTagByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteRevisionTagByIDParamsWithContext(ctx context.Context) *DeleteRevisionTagByIDParams {
	var ()
	return &DeleteRevisionTagByIDParams{

		Context: ctx,
	}
}

// NewDeleteRevisionTagByIDParamsWithHTTPClient creates a new DeleteRevisionTagByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteRevisionTagByIDParamsWithHTTPClient(client *http.Client) *DeleteRevisionTagByIDParams {
	var ()
	return &DeleteRevisionTagByIDParams{
		HTTPClient: client,
	}
}

/*DeleteRevisionTagByIDParams contains all the parameters to send to the API endpoint
for the delete revision tag by Id operation typically these are written to a http.Request
*/
type DeleteRevisionTagByIDParams struct {

	/*XAuthToken
	  A fernet keystone bearer token used for authentication and authorization

	*/
	XAuthToken *string
	/*RevisionID*/
	RevisionID string
	/*Tag*/
	Tag string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete revision tag by Id params
func (o *DeleteRevisionTagByIDParams) WithTimeout(timeout time.Duration) *DeleteRevisionTagByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete revision tag by Id params
func (o *DeleteRevisionTagByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete revision tag by Id params
func (o *DeleteRevisionTagByIDParams) WithContext(ctx context.Context) *DeleteRevisionTagByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete revision tag by Id params
func (o *DeleteRevisionTagByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete revision tag by Id params
func (o *DeleteRevisionTagByIDParams) WithHTTPClient(client *http.Client) *DeleteRevisionTagByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete revision tag by Id params
func (o *DeleteRevisionTagByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAuthToken adds the xAuthToken to the delete revision tag by Id params
func (o *DeleteRevisionTagByIDParams) WithXAuthToken(xAuthToken *string) *DeleteRevisionTagByIDParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the delete revision tag by Id params
func (o *DeleteRevisionTagByIDParams) SetXAuthToken(xAuthToken *string) {
	o.XAuthToken = xAuthToken
}

// WithRevisionID adds the revisionID to the delete revision tag by Id params
func (o *DeleteRevisionTagByIDParams) WithRevisionID(revisionID string) *DeleteRevisionTagByIDParams {
	o.SetRevisionID(revisionID)
	return o
}

// SetRevisionID adds the revisionId to the delete revision tag by Id params
func (o *DeleteRevisionTagByIDParams) SetRevisionID(revisionID string) {
	o.RevisionID = revisionID
}

// WithTag adds the tag to the delete revision tag by Id params
func (o *DeleteRevisionTagByIDParams) WithTag(tag string) *DeleteRevisionTagByIDParams {
	o.SetTag(tag)
	return o
}

// SetTag adds the tag to the delete revision tag by Id params
func (o *DeleteRevisionTagByIDParams) SetTag(tag string) {
	o.Tag = tag
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteRevisionTagByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XAuthToken != nil {

		// header param X-Auth-Token
		if err := r.SetHeaderParam("X-Auth-Token", *o.XAuthToken); err != nil {
			return err
		}

	}

	// path param revision-id
	if err := r.SetPathParam("revision-id", o.RevisionID); err != nil {
		return err
	}

	// path param tag
	if err := r.SetPathParam("tag", o.Tag); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
