// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetValidationEntryByIDReader is a Reader for the GetValidationEntryByID structure.
type GetValidationEntryByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetValidationEntryByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetValidationEntryByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetValidationEntryByIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetValidationEntryByIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetValidationEntryByIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetValidationEntryByIDOK creates a GetValidationEntryByIDOK with default headers values
func NewGetValidationEntryByIDOK() *GetValidationEntryByIDOK {
	return &GetValidationEntryByIDOK{}
}

/*GetValidationEntryByIDOK handles this case with default header values.

Generic String answer
*/
type GetValidationEntryByIDOK struct {
	Payload string
}

func (o *GetValidationEntryByIDOK) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/revisions/{revision-id}/validations/{validation-name}/entries/{entry-id}][%d] getValidationEntryByIdOK  %+v", 200, o.Payload)
}

func (o *GetValidationEntryByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetValidationEntryByIDUnauthorized creates a GetValidationEntryByIDUnauthorized with default headers values
func NewGetValidationEntryByIDUnauthorized() *GetValidationEntryByIDUnauthorized {
	return &GetValidationEntryByIDUnauthorized{}
}

/*GetValidationEntryByIDUnauthorized handles this case with default header values.

401 Not authorized
*/
type GetValidationEntryByIDUnauthorized struct {
}

func (o *GetValidationEntryByIDUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/revisions/{revision-id}/validations/{validation-name}/entries/{entry-id}][%d] getValidationEntryByIdUnauthorized ", 401)
}

func (o *GetValidationEntryByIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetValidationEntryByIDForbidden creates a GetValidationEntryByIDForbidden with default headers values
func NewGetValidationEntryByIDForbidden() *GetValidationEntryByIDForbidden {
	return &GetValidationEntryByIDForbidden{}
}

/*GetValidationEntryByIDForbidden handles this case with default header values.

403 Forbidden
*/
type GetValidationEntryByIDForbidden struct {
}

func (o *GetValidationEntryByIDForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/revisions/{revision-id}/validations/{validation-name}/entries/{entry-id}][%d] getValidationEntryByIdForbidden ", 403)
}

func (o *GetValidationEntryByIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetValidationEntryByIDInternalServerError creates a GetValidationEntryByIDInternalServerError with default headers values
func NewGetValidationEntryByIDInternalServerError() *GetValidationEntryByIDInternalServerError {
	return &GetValidationEntryByIDInternalServerError{}
}

/*GetValidationEntryByIDInternalServerError handles this case with default header values.

500 Internal Server Error
*/
type GetValidationEntryByIDInternalServerError struct {
}

func (o *GetValidationEntryByIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/revisions/{revision-id}/validations/{validation-name}/entries/{entry-id}][%d] getValidationEntryByIdInternalServerError ", 500)
}

func (o *GetValidationEntryByIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
