// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetRenderedDocumentsByIDReader is a Reader for the GetRenderedDocumentsByID structure.
type GetRenderedDocumentsByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRenderedDocumentsByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetRenderedDocumentsByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetRenderedDocumentsByIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetRenderedDocumentsByIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetRenderedDocumentsByIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetRenderedDocumentsByIDOK creates a GetRenderedDocumentsByIDOK with default headers values
func NewGetRenderedDocumentsByIDOK() *GetRenderedDocumentsByIDOK {
	return &GetRenderedDocumentsByIDOK{}
}

/*GetRenderedDocumentsByIDOK handles this case with default header values.

Generic String answer
*/
type GetRenderedDocumentsByIDOK struct {
	Payload string
}

func (o *GetRenderedDocumentsByIDOK) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/revisions/{revision-id}/rendered-documents][%d] getRenderedDocumentsByIdOK  %+v", 200, o.Payload)
}

func (o *GetRenderedDocumentsByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRenderedDocumentsByIDUnauthorized creates a GetRenderedDocumentsByIDUnauthorized with default headers values
func NewGetRenderedDocumentsByIDUnauthorized() *GetRenderedDocumentsByIDUnauthorized {
	return &GetRenderedDocumentsByIDUnauthorized{}
}

/*GetRenderedDocumentsByIDUnauthorized handles this case with default header values.

401 Not authorized
*/
type GetRenderedDocumentsByIDUnauthorized struct {
}

func (o *GetRenderedDocumentsByIDUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/revisions/{revision-id}/rendered-documents][%d] getRenderedDocumentsByIdUnauthorized ", 401)
}

func (o *GetRenderedDocumentsByIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetRenderedDocumentsByIDForbidden creates a GetRenderedDocumentsByIDForbidden with default headers values
func NewGetRenderedDocumentsByIDForbidden() *GetRenderedDocumentsByIDForbidden {
	return &GetRenderedDocumentsByIDForbidden{}
}

/*GetRenderedDocumentsByIDForbidden handles this case with default header values.

403 Forbidden
*/
type GetRenderedDocumentsByIDForbidden struct {
}

func (o *GetRenderedDocumentsByIDForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/revisions/{revision-id}/rendered-documents][%d] getRenderedDocumentsByIdForbidden ", 403)
}

func (o *GetRenderedDocumentsByIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetRenderedDocumentsByIDInternalServerError creates a GetRenderedDocumentsByIDInternalServerError with default headers values
func NewGetRenderedDocumentsByIDInternalServerError() *GetRenderedDocumentsByIDInternalServerError {
	return &GetRenderedDocumentsByIDInternalServerError{}
}

/*GetRenderedDocumentsByIDInternalServerError handles this case with default header values.

500 Internal Server Error
*/
type GetRenderedDocumentsByIDInternalServerError struct {
}

func (o *GetRenderedDocumentsByIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/revisions/{revision-id}/rendered-documents][%d] getRenderedDocumentsByIdInternalServerError ", 500)
}

func (o *GetRenderedDocumentsByIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
