// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewShowRevisionDiffParams creates a new ShowRevisionDiffParams object
// with the default values initialized.
func NewShowRevisionDiffParams() *ShowRevisionDiffParams {
	var ()
	return &ShowRevisionDiffParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewShowRevisionDiffParamsWithTimeout creates a new ShowRevisionDiffParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewShowRevisionDiffParamsWithTimeout(timeout time.Duration) *ShowRevisionDiffParams {
	var ()
	return &ShowRevisionDiffParams{

		timeout: timeout,
	}
}

// NewShowRevisionDiffParamsWithContext creates a new ShowRevisionDiffParams object
// with the default values initialized, and the ability to set a context for a request
func NewShowRevisionDiffParamsWithContext(ctx context.Context) *ShowRevisionDiffParams {
	var ()
	return &ShowRevisionDiffParams{

		Context: ctx,
	}
}

// NewShowRevisionDiffParamsWithHTTPClient creates a new ShowRevisionDiffParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewShowRevisionDiffParamsWithHTTPClient(client *http.Client) *ShowRevisionDiffParams {
	var ()
	return &ShowRevisionDiffParams{
		HTTPClient: client,
	}
}

/*ShowRevisionDiffParams contains all the parameters to send to the API endpoint
for the show revision diff operation typically these are written to a http.Request
*/
type ShowRevisionDiffParams struct {

	/*XAuthToken
	  A fernet keystone bearer token used for authentication and authorization

	*/
	XAuthToken *string
	/*ComparisonRevisionID*/
	ComparisonRevisionID string
	/*RevisionID*/
	RevisionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the show revision diff params
func (o *ShowRevisionDiffParams) WithTimeout(timeout time.Duration) *ShowRevisionDiffParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the show revision diff params
func (o *ShowRevisionDiffParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the show revision diff params
func (o *ShowRevisionDiffParams) WithContext(ctx context.Context) *ShowRevisionDiffParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the show revision diff params
func (o *ShowRevisionDiffParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the show revision diff params
func (o *ShowRevisionDiffParams) WithHTTPClient(client *http.Client) *ShowRevisionDiffParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the show revision diff params
func (o *ShowRevisionDiffParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAuthToken adds the xAuthToken to the show revision diff params
func (o *ShowRevisionDiffParams) WithXAuthToken(xAuthToken *string) *ShowRevisionDiffParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the show revision diff params
func (o *ShowRevisionDiffParams) SetXAuthToken(xAuthToken *string) {
	o.XAuthToken = xAuthToken
}

// WithComparisonRevisionID adds the comparisonRevisionID to the show revision diff params
func (o *ShowRevisionDiffParams) WithComparisonRevisionID(comparisonRevisionID string) *ShowRevisionDiffParams {
	o.SetComparisonRevisionID(comparisonRevisionID)
	return o
}

// SetComparisonRevisionID adds the comparisonRevisionId to the show revision diff params
func (o *ShowRevisionDiffParams) SetComparisonRevisionID(comparisonRevisionID string) {
	o.ComparisonRevisionID = comparisonRevisionID
}

// WithRevisionID adds the revisionID to the show revision diff params
func (o *ShowRevisionDiffParams) WithRevisionID(revisionID string) *ShowRevisionDiffParams {
	o.SetRevisionID(revisionID)
	return o
}

// SetRevisionID adds the revisionId to the show revision diff params
func (o *ShowRevisionDiffParams) SetRevisionID(revisionID string) {
	o.RevisionID = revisionID
}

// WriteToRequest writes these params to a swagger request
func (o *ShowRevisionDiffParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XAuthToken != nil {

		// header param X-Auth-Token
		if err := r.SetHeaderParam("X-Auth-Token", *o.XAuthToken); err != nil {
			return err
		}

	}

	// path param comparison-revision-id
	if err := r.SetPathParam("comparison-revision-id", o.ComparisonRevisionID); err != nil {
		return err
	}

	// path param revision-id
	if err := r.SetPathParam("revision-id", o.RevisionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
