apiVersion: v1
kind: Namespace
metadata:
  name: apisim
---
apiVersion: v1
kind: Pod
metadata:
  name: deckhand
  namespace: apisim
spec:
  containers:
  - name: deckhand
    image: kubekit99/apisim-deckhand:0.1.0
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: drydock
  namespace: apisim
spec:
  containers:
  - name: drydock
    image: kubekit99/apisim-drydock:0.1.0
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: armada
  namespace: apisim
spec:
  containers:
  - name: armada
    image: kubekit99/apisim-armada:0.1.0
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: promenade
  namespace: apisim
spec:
  containers:
  - name: promenade
    image: kubekit99/apisim-promenade:0.1.0
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: shipyard
  namespace: apisim
spec:
  containers:
  - name: shipyard
    image: kubekit99/apisim-shipyard:0.1.0
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
