// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Shipyard
Shipyard provides operators a way to deploy or upgrade collection of helm
charts using a single command.



    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 0.1.0
    License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
    Contact: Shipyard Github Repository https://github.com/openstack/airship-shipyard

    Consumes:
    - application/json
    - application/x-yaml

    Produces:
    - text/plain

swagger:meta
*/
package restapi
