// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteRevisionTagByIDHandlerFunc turns a function with the right signature into a delete revision tag by Id handler
type DeleteRevisionTagByIDHandlerFunc func(DeleteRevisionTagByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteRevisionTagByIDHandlerFunc) Handle(params DeleteRevisionTagByIDParams) middleware.Responder {
	return fn(params)
}

// DeleteRevisionTagByIDHandler interface for that can handle valid delete revision tag by Id params
type DeleteRevisionTagByIDHandler interface {
	Handle(DeleteRevisionTagByIDParams) middleware.Responder
}

// NewDeleteRevisionTagByID creates a new http.Handler for the delete revision tag by Id operation
func NewDeleteRevisionTagByID(ctx *middleware.Context, handler DeleteRevisionTagByIDHandler) *DeleteRevisionTagByID {
	return &DeleteRevisionTagByID{Context: ctx, Handler: handler}
}

/*DeleteRevisionTagByID swagger:route DELETE /api/v1.0/revisions/{revision-id}/tags/{tag} deleteRevisionTagById

Delete a revision tag.

*/
type DeleteRevisionTagByID struct {
	Context *middleware.Context
	Handler DeleteRevisionTagByIDHandler
}

func (o *DeleteRevisionTagByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteRevisionTagByIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
