// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetValidationByIDOKCode is the HTTP code returned for type GetValidationByIDOK
const GetValidationByIDOKCode int = 200

/*GetValidationByIDOK Generic String answer

swagger:response getValidationByIdOK
*/
type GetValidationByIDOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetValidationByIDOK creates GetValidationByIDOK with default headers values
func NewGetValidationByIDOK() *GetValidationByIDOK {

	return &GetValidationByIDOK{}
}

// WithPayload adds the payload to the get validation by Id o k response
func (o *GetValidationByIDOK) WithPayload(payload string) *GetValidationByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get validation by Id o k response
func (o *GetValidationByIDOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetValidationByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetValidationByIDUnauthorizedCode is the HTTP code returned for type GetValidationByIDUnauthorized
const GetValidationByIDUnauthorizedCode int = 401

/*GetValidationByIDUnauthorized 401 Not authorized

swagger:response getValidationByIdUnauthorized
*/
type GetValidationByIDUnauthorized struct {
}

// NewGetValidationByIDUnauthorized creates GetValidationByIDUnauthorized with default headers values
func NewGetValidationByIDUnauthorized() *GetValidationByIDUnauthorized {

	return &GetValidationByIDUnauthorized{}
}

// WriteResponse to the client
func (o *GetValidationByIDUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetValidationByIDForbiddenCode is the HTTP code returned for type GetValidationByIDForbidden
const GetValidationByIDForbiddenCode int = 403

/*GetValidationByIDForbidden 403 Forbidden

swagger:response getValidationByIdForbidden
*/
type GetValidationByIDForbidden struct {
}

// NewGetValidationByIDForbidden creates GetValidationByIDForbidden with default headers values
func NewGetValidationByIDForbidden() *GetValidationByIDForbidden {

	return &GetValidationByIDForbidden{}
}

// WriteResponse to the client
func (o *GetValidationByIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// GetValidationByIDInternalServerErrorCode is the HTTP code returned for type GetValidationByIDInternalServerError
const GetValidationByIDInternalServerErrorCode int = 500

/*GetValidationByIDInternalServerError 500 Internal Server Error

swagger:response getValidationByIdInternalServerError
*/
type GetValidationByIDInternalServerError struct {
}

// NewGetValidationByIDInternalServerError creates GetValidationByIDInternalServerError with default headers values
func NewGetValidationByIDInternalServerError() *GetValidationByIDInternalServerError {

	return &GetValidationByIDInternalServerError{}
}

// WriteResponse to the client
func (o *GetValidationByIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
