// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAllValidationsHandlerFunc turns a function with the right signature into a get all validations handler
type GetAllValidationsHandlerFunc func(GetAllValidationsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAllValidationsHandlerFunc) Handle(params GetAllValidationsParams) middleware.Responder {
	return fn(params)
}

// GetAllValidationsHandler interface for that can handle valid get all validations params
type GetAllValidationsHandler interface {
	Handle(GetAllValidationsParams) middleware.Responder
}

// NewGetAllValidations creates a new http.Handler for the get all validations operation
func NewGetAllValidations(ctx *middleware.Context, handler GetAllValidationsHandler) *GetAllValidations {
	return &GetAllValidations{Context: ctx, Handler: handler}
}

/*GetAllValidations swagger:route GET /api/v1.0/revisions/{revision-id}/validations getAllValidations

List all validations that have been reported for a revision. Also lists the validation entries for a particular validation.

*/
type GetAllValidations struct {
	Context *middleware.Context
	Handler GetAllValidationsHandler
}

func (o *GetAllValidations) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAllValidationsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
