// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// RollbackRevisionOKCode is the HTTP code returned for type RollbackRevisionOK
const RollbackRevisionOKCode int = 200

/*RollbackRevisionOK Generic String answer

swagger:response rollbackRevisionOK
*/
type RollbackRevisionOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewRollbackRevisionOK creates RollbackRevisionOK with default headers values
func NewRollbackRevisionOK() *RollbackRevisionOK {

	return &RollbackRevisionOK{}
}

// WithPayload adds the payload to the rollback revision o k response
func (o *RollbackRevisionOK) WithPayload(payload string) *RollbackRevisionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the rollback revision o k response
func (o *RollbackRevisionOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RollbackRevisionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// RollbackRevisionUnauthorizedCode is the HTTP code returned for type RollbackRevisionUnauthorized
const RollbackRevisionUnauthorizedCode int = 401

/*RollbackRevisionUnauthorized 401 Not authorized

swagger:response rollbackRevisionUnauthorized
*/
type RollbackRevisionUnauthorized struct {
}

// NewRollbackRevisionUnauthorized creates RollbackRevisionUnauthorized with default headers values
func NewRollbackRevisionUnauthorized() *RollbackRevisionUnauthorized {

	return &RollbackRevisionUnauthorized{}
}

// WriteResponse to the client
func (o *RollbackRevisionUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// RollbackRevisionForbiddenCode is the HTTP code returned for type RollbackRevisionForbidden
const RollbackRevisionForbiddenCode int = 403

/*RollbackRevisionForbidden 403 Forbidden

swagger:response rollbackRevisionForbidden
*/
type RollbackRevisionForbidden struct {
}

// NewRollbackRevisionForbidden creates RollbackRevisionForbidden with default headers values
func NewRollbackRevisionForbidden() *RollbackRevisionForbidden {

	return &RollbackRevisionForbidden{}
}

// WriteResponse to the client
func (o *RollbackRevisionForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// RollbackRevisionInternalServerErrorCode is the HTTP code returned for type RollbackRevisionInternalServerError
const RollbackRevisionInternalServerErrorCode int = 500

/*RollbackRevisionInternalServerError 500 Internal Server Error

swagger:response rollbackRevisionInternalServerError
*/
type RollbackRevisionInternalServerError struct {
}

// NewRollbackRevisionInternalServerError creates RollbackRevisionInternalServerError with default headers values
func NewRollbackRevisionInternalServerError() *RollbackRevisionInternalServerError {

	return &RollbackRevisionInternalServerError{}
}

// WriteResponse to the client
func (o *RollbackRevisionInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
