// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"
)

// ShowRevisionDeepDiffURL generates an URL for the show revision deep diff operation
type ShowRevisionDeepDiffURL struct {
	ComparisonRevisionID string
	RevisionID           string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *ShowRevisionDeepDiffURL) WithBasePath(bp string) *ShowRevisionDeepDiffURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *ShowRevisionDeepDiffURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *ShowRevisionDeepDiffURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/api/v1.0/revisions/{revision-id}/deepdiff/{comparison-revision-id}"

	comparisonRevisionID := o.ComparisonRevisionID
	if comparisonRevisionID != "" {
		_path = strings.Replace(_path, "{comparison-revision-id}", comparisonRevisionID, -1)
	} else {
		return nil, errors.New("comparisonRevisionId is required on ShowRevisionDeepDiffURL")
	}

	revisionID := o.RevisionID
	if revisionID != "" {
		_path = strings.Replace(_path, "{revision-id}", revisionID, -1)
	} else {
		return nil, errors.New("revisionId is required on ShowRevisionDeepDiffURL")
	}

	_basePath := o._basePath
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *ShowRevisionDeepDiffURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *ShowRevisionDeepDiffURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *ShowRevisionDeepDiffURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on ShowRevisionDeepDiffURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on ShowRevisionDeepDiffURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *ShowRevisionDeepDiffURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
