// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// Metadata metadata
// swagger:model metadata
type Metadata map[string]string

// Validate validates this metadata
func (m Metadata) Validate(formats strfmt.Registry) error {
	return nil
}
