// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCreateRelabelNodesTaskParams creates a new CreateRelabelNodesTaskParams object
// with the default values initialized.
func NewCreateRelabelNodesTaskParams() *CreateRelabelNodesTaskParams {
	var ()
	return &CreateRelabelNodesTaskParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateRelabelNodesTaskParamsWithTimeout creates a new CreateRelabelNodesTaskParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateRelabelNodesTaskParamsWithTimeout(timeout time.Duration) *CreateRelabelNodesTaskParams {
	var ()
	return &CreateRelabelNodesTaskParams{

		timeout: timeout,
	}
}

// NewCreateRelabelNodesTaskParamsWithContext creates a new CreateRelabelNodesTaskParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateRelabelNodesTaskParamsWithContext(ctx context.Context) *CreateRelabelNodesTaskParams {
	var ()
	return &CreateRelabelNodesTaskParams{

		Context: ctx,
	}
}

// NewCreateRelabelNodesTaskParamsWithHTTPClient creates a new CreateRelabelNodesTaskParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateRelabelNodesTaskParamsWithHTTPClient(client *http.Client) *CreateRelabelNodesTaskParams {
	var ()
	return &CreateRelabelNodesTaskParams{
		HTTPClient: client,
	}
}

/*CreateRelabelNodesTaskParams contains all the parameters to send to the API endpoint
for the create relabel nodes task operation typically these are written to a http.Request
*/
type CreateRelabelNodesTaskParams struct {

	/*XAuthToken
	  A fernet keystone bearer token used for authentication and authorization

	*/
	XAuthToken *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create relabel nodes task params
func (o *CreateRelabelNodesTaskParams) WithTimeout(timeout time.Duration) *CreateRelabelNodesTaskParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create relabel nodes task params
func (o *CreateRelabelNodesTaskParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create relabel nodes task params
func (o *CreateRelabelNodesTaskParams) WithContext(ctx context.Context) *CreateRelabelNodesTaskParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create relabel nodes task params
func (o *CreateRelabelNodesTaskParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create relabel nodes task params
func (o *CreateRelabelNodesTaskParams) WithHTTPClient(client *http.Client) *CreateRelabelNodesTaskParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create relabel nodes task params
func (o *CreateRelabelNodesTaskParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAuthToken adds the xAuthToken to the create relabel nodes task params
func (o *CreateRelabelNodesTaskParams) WithXAuthToken(xAuthToken *string) *CreateRelabelNodesTaskParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the create relabel nodes task params
func (o *CreateRelabelNodesTaskParams) SetXAuthToken(xAuthToken *string) {
	o.XAuthToken = xAuthToken
}

// WriteToRequest writes these params to a swagger request
func (o *CreateRelabelNodesTaskParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XAuthToken != nil {

		// header param X-Auth-Token
		if err := r.SetHeaderParam("X-Auth-Token", *o.XAuthToken); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
