// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetTaskStatusByIDParams creates a new GetTaskStatusByIDParams object
// with the default values initialized.
func NewGetTaskStatusByIDParams() *GetTaskStatusByIDParams {
	var ()
	return &GetTaskStatusByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTaskStatusByIDParamsWithTimeout creates a new GetTaskStatusByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTaskStatusByIDParamsWithTimeout(timeout time.Duration) *GetTaskStatusByIDParams {
	var ()
	return &GetTaskStatusByIDParams{

		timeout: timeout,
	}
}

// NewGetTaskStatusByIDParamsWithContext creates a new GetTaskStatusByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTaskStatusByIDParamsWithContext(ctx context.Context) *GetTaskStatusByIDParams {
	var ()
	return &GetTaskStatusByIDParams{

		Context: ctx,
	}
}

// NewGetTaskStatusByIDParamsWithHTTPClient creates a new GetTaskStatusByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTaskStatusByIDParamsWithHTTPClient(client *http.Client) *GetTaskStatusByIDParams {
	var ()
	return &GetTaskStatusByIDParams{
		HTTPClient: client,
	}
}

/*GetTaskStatusByIDParams contains all the parameters to send to the API endpoint
for the get task status by Id operation typically these are written to a http.Request
*/
type GetTaskStatusByIDParams struct {

	/*XAuthToken
	  A fernet keystone bearer token used for authentication and authorization

	*/
	XAuthToken *string
	/*TaskID*/
	TaskID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get task status by Id params
func (o *GetTaskStatusByIDParams) WithTimeout(timeout time.Duration) *GetTaskStatusByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get task status by Id params
func (o *GetTaskStatusByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get task status by Id params
func (o *GetTaskStatusByIDParams) WithContext(ctx context.Context) *GetTaskStatusByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get task status by Id params
func (o *GetTaskStatusByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get task status by Id params
func (o *GetTaskStatusByIDParams) WithHTTPClient(client *http.Client) *GetTaskStatusByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get task status by Id params
func (o *GetTaskStatusByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAuthToken adds the xAuthToken to the get task status by Id params
func (o *GetTaskStatusByIDParams) WithXAuthToken(xAuthToken *string) *GetTaskStatusByIDParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the get task status by Id params
func (o *GetTaskStatusByIDParams) SetXAuthToken(xAuthToken *string) {
	o.XAuthToken = xAuthToken
}

// WithTaskID adds the taskID to the get task status by Id params
func (o *GetTaskStatusByIDParams) WithTaskID(taskID string) *GetTaskStatusByIDParams {
	o.SetTaskID(taskID)
	return o
}

// SetTaskID adds the taskId to the get task status by Id params
func (o *GetTaskStatusByIDParams) SetTaskID(taskID string) {
	o.TaskID = taskID
}

// WriteToRequest writes these params to a swagger request
func (o *GetTaskStatusByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XAuthToken != nil {

		// header param X-Auth-Token
		if err := r.SetHeaderParam("X-Auth-Token", *o.XAuthToken); err != nil {
			return err
		}

	}

	// path param task-id
	if err := r.SetPathParam("task-id", o.TaskID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
