// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// LoadDesignDataPartsReader is a Reader for the LoadDesignDataParts structure.
type LoadDesignDataPartsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LoadDesignDataPartsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewLoadDesignDataPartsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewLoadDesignDataPartsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewLoadDesignDataPartsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewLoadDesignDataPartsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewLoadDesignDataPartsOK creates a LoadDesignDataPartsOK with default headers values
func NewLoadDesignDataPartsOK() *LoadDesignDataPartsOK {
	return &LoadDesignDataPartsOK{}
}

/*LoadDesignDataPartsOK handles this case with default header values.

Generic String answer
*/
type LoadDesignDataPartsOK struct {
	Payload string
}

func (o *LoadDesignDataPartsOK) Error() string {
	return fmt.Sprintf("[POST /api/v1.0/designs/{design-id}/parts][%d] loadDesignDataPartsOK  %+v", 200, o.Payload)
}

func (o *LoadDesignDataPartsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLoadDesignDataPartsUnauthorized creates a LoadDesignDataPartsUnauthorized with default headers values
func NewLoadDesignDataPartsUnauthorized() *LoadDesignDataPartsUnauthorized {
	return &LoadDesignDataPartsUnauthorized{}
}

/*LoadDesignDataPartsUnauthorized handles this case with default header values.

401 Not authorized
*/
type LoadDesignDataPartsUnauthorized struct {
}

func (o *LoadDesignDataPartsUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/v1.0/designs/{design-id}/parts][%d] loadDesignDataPartsUnauthorized ", 401)
}

func (o *LoadDesignDataPartsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewLoadDesignDataPartsForbidden creates a LoadDesignDataPartsForbidden with default headers values
func NewLoadDesignDataPartsForbidden() *LoadDesignDataPartsForbidden {
	return &LoadDesignDataPartsForbidden{}
}

/*LoadDesignDataPartsForbidden handles this case with default header values.

403 Forbidden
*/
type LoadDesignDataPartsForbidden struct {
}

func (o *LoadDesignDataPartsForbidden) Error() string {
	return fmt.Sprintf("[POST /api/v1.0/designs/{design-id}/parts][%d] loadDesignDataPartsForbidden ", 403)
}

func (o *LoadDesignDataPartsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewLoadDesignDataPartsInternalServerError creates a LoadDesignDataPartsInternalServerError with default headers values
func NewLoadDesignDataPartsInternalServerError() *LoadDesignDataPartsInternalServerError {
	return &LoadDesignDataPartsInternalServerError{}
}

/*LoadDesignDataPartsInternalServerError handles this case with default header values.

500 Internal Server Error
*/
type LoadDesignDataPartsInternalServerError struct {
}

func (o *LoadDesignDataPartsInternalServerError) Error() string {
	return fmt.Sprintf("[POST /api/v1.0/designs/{design-id}/parts][%d] loadDesignDataPartsInternalServerError ", 500)
}

func (o *LoadDesignDataPartsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
