// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewReadBuildDataForANodeParams creates a new ReadBuildDataForANodeParams object
// with the default values initialized.
func NewReadBuildDataForANodeParams() *ReadBuildDataForANodeParams {
	var ()
	return &ReadBuildDataForANodeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewReadBuildDataForANodeParamsWithTimeout creates a new ReadBuildDataForANodeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewReadBuildDataForANodeParamsWithTimeout(timeout time.Duration) *ReadBuildDataForANodeParams {
	var ()
	return &ReadBuildDataForANodeParams{

		timeout: timeout,
	}
}

// NewReadBuildDataForANodeParamsWithContext creates a new ReadBuildDataForANodeParams object
// with the default values initialized, and the ability to set a context for a request
func NewReadBuildDataForANodeParamsWithContext(ctx context.Context) *ReadBuildDataForANodeParams {
	var ()
	return &ReadBuildDataForANodeParams{

		Context: ctx,
	}
}

// NewReadBuildDataForANodeParamsWithHTTPClient creates a new ReadBuildDataForANodeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewReadBuildDataForANodeParamsWithHTTPClient(client *http.Client) *ReadBuildDataForANodeParams {
	var ()
	return &ReadBuildDataForANodeParams{
		HTTPClient: client,
	}
}

/*ReadBuildDataForANodeParams contains all the parameters to send to the API endpoint
for the read build data for a node operation typically these are written to a http.Request
*/
type ReadBuildDataForANodeParams struct {

	/*XAuthToken
	  A fernet keystone bearer token used for authentication and authorization

	*/
	XAuthToken *string
	/*Nodename*/
	Nodename string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the read build data for a node params
func (o *ReadBuildDataForANodeParams) WithTimeout(timeout time.Duration) *ReadBuildDataForANodeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the read build data for a node params
func (o *ReadBuildDataForANodeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the read build data for a node params
func (o *ReadBuildDataForANodeParams) WithContext(ctx context.Context) *ReadBuildDataForANodeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the read build data for a node params
func (o *ReadBuildDataForANodeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the read build data for a node params
func (o *ReadBuildDataForANodeParams) WithHTTPClient(client *http.Client) *ReadBuildDataForANodeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the read build data for a node params
func (o *ReadBuildDataForANodeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAuthToken adds the xAuthToken to the read build data for a node params
func (o *ReadBuildDataForANodeParams) WithXAuthToken(xAuthToken *string) *ReadBuildDataForANodeParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the read build data for a node params
func (o *ReadBuildDataForANodeParams) SetXAuthToken(xAuthToken *string) {
	o.XAuthToken = xAuthToken
}

// WithNodename adds the nodename to the read build data for a node params
func (o *ReadBuildDataForANodeParams) WithNodename(nodename string) *ReadBuildDataForANodeParams {
	o.SetNodename(nodename)
	return o
}

// SetNodename adds the nodename to the read build data for a node params
func (o *ReadBuildDataForANodeParams) SetNodename(nodename string) {
	o.Nodename = nodename
}

// WriteToRequest writes these params to a swagger request
func (o *ReadBuildDataForANodeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XAuthToken != nil {

		// header param X-Auth-Token
		if err := r.SetHeaderParam("X-Auth-Token", *o.XAuthToken); err != nil {
			return err
		}

	}

	// path param nodename
	if err := r.SetPathParam("nodename", o.Nodename); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
