// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// ReadBuildDataForANodeReader is a Reader for the ReadBuildDataForANode structure.
type ReadBuildDataForANodeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReadBuildDataForANodeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewReadBuildDataForANodeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewReadBuildDataForANodeUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewReadBuildDataForANodeForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewReadBuildDataForANodeInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewReadBuildDataForANodeOK creates a ReadBuildDataForANodeOK with default headers values
func NewReadBuildDataForANodeOK() *ReadBuildDataForANodeOK {
	return &ReadBuildDataForANodeOK{}
}

/*ReadBuildDataForANodeOK handles this case with default header values.

Generic String answer
*/
type ReadBuildDataForANodeOK struct {
	Payload string
}

func (o *ReadBuildDataForANodeOK) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/nodes/{nodename}/builddata][%d] readBuildDataForANodeOK  %+v", 200, o.Payload)
}

func (o *ReadBuildDataForANodeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReadBuildDataForANodeUnauthorized creates a ReadBuildDataForANodeUnauthorized with default headers values
func NewReadBuildDataForANodeUnauthorized() *ReadBuildDataForANodeUnauthorized {
	return &ReadBuildDataForANodeUnauthorized{}
}

/*ReadBuildDataForANodeUnauthorized handles this case with default header values.

401 Not authorized
*/
type ReadBuildDataForANodeUnauthorized struct {
}

func (o *ReadBuildDataForANodeUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/nodes/{nodename}/builddata][%d] readBuildDataForANodeUnauthorized ", 401)
}

func (o *ReadBuildDataForANodeUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewReadBuildDataForANodeForbidden creates a ReadBuildDataForANodeForbidden with default headers values
func NewReadBuildDataForANodeForbidden() *ReadBuildDataForANodeForbidden {
	return &ReadBuildDataForANodeForbidden{}
}

/*ReadBuildDataForANodeForbidden handles this case with default header values.

403 Forbidden
*/
type ReadBuildDataForANodeForbidden struct {
}

func (o *ReadBuildDataForANodeForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/nodes/{nodename}/builddata][%d] readBuildDataForANodeForbidden ", 403)
}

func (o *ReadBuildDataForANodeForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewReadBuildDataForANodeInternalServerError creates a ReadBuildDataForANodeInternalServerError with default headers values
func NewReadBuildDataForANodeInternalServerError() *ReadBuildDataForANodeInternalServerError {
	return &ReadBuildDataForANodeInternalServerError{}
}

/*ReadBuildDataForANodeInternalServerError handles this case with default header values.

500 Internal Server Error
*/
type ReadBuildDataForANodeInternalServerError struct {
}

func (o *ReadBuildDataForANodeInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/nodes/{nodename}/builddata][%d] readBuildDataForANodeInternalServerError ", 500)
}

func (o *ReadBuildDataForANodeInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
