// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Promenade
Promenade



    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 0.1.0
    License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
    Contact: Promenade Github Repository https://github.com/openstack/airship-promenade

    Consumes:
    - application/json

    Produces:
    - text/plain

swagger:meta
*/
package restapi
