// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// CreateRelabelNodesTaskOKCode is the HTTP code returned for type CreateRelabelNodesTaskOK
const CreateRelabelNodesTaskOKCode int = 200

/*CreateRelabelNodesTaskOK Generic String answer

swagger:response createRelabelNodesTaskOK
*/
type CreateRelabelNodesTaskOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewCreateRelabelNodesTaskOK creates CreateRelabelNodesTaskOK with default headers values
func NewCreateRelabelNodesTaskOK() *CreateRelabelNodesTaskOK {

	return &CreateRelabelNodesTaskOK{}
}

// WithPayload adds the payload to the create relabel nodes task o k response
func (o *CreateRelabelNodesTaskOK) WithPayload(payload string) *CreateRelabelNodesTaskOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create relabel nodes task o k response
func (o *CreateRelabelNodesTaskOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateRelabelNodesTaskOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// CreateRelabelNodesTaskUnauthorizedCode is the HTTP code returned for type CreateRelabelNodesTaskUnauthorized
const CreateRelabelNodesTaskUnauthorizedCode int = 401

/*CreateRelabelNodesTaskUnauthorized 401 Not authorized

swagger:response createRelabelNodesTaskUnauthorized
*/
type CreateRelabelNodesTaskUnauthorized struct {
}

// NewCreateRelabelNodesTaskUnauthorized creates CreateRelabelNodesTaskUnauthorized with default headers values
func NewCreateRelabelNodesTaskUnauthorized() *CreateRelabelNodesTaskUnauthorized {

	return &CreateRelabelNodesTaskUnauthorized{}
}

// WriteResponse to the client
func (o *CreateRelabelNodesTaskUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// CreateRelabelNodesTaskForbiddenCode is the HTTP code returned for type CreateRelabelNodesTaskForbidden
const CreateRelabelNodesTaskForbiddenCode int = 403

/*CreateRelabelNodesTaskForbidden 403 Forbidden

swagger:response createRelabelNodesTaskForbidden
*/
type CreateRelabelNodesTaskForbidden struct {
}

// NewCreateRelabelNodesTaskForbidden creates CreateRelabelNodesTaskForbidden with default headers values
func NewCreateRelabelNodesTaskForbidden() *CreateRelabelNodesTaskForbidden {

	return &CreateRelabelNodesTaskForbidden{}
}

// WriteResponse to the client
func (o *CreateRelabelNodesTaskForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// CreateRelabelNodesTaskInternalServerErrorCode is the HTTP code returned for type CreateRelabelNodesTaskInternalServerError
const CreateRelabelNodesTaskInternalServerErrorCode int = 500

/*CreateRelabelNodesTaskInternalServerError 500 Internal Server Error

swagger:response createRelabelNodesTaskInternalServerError
*/
type CreateRelabelNodesTaskInternalServerError struct {
}

// NewCreateRelabelNodesTaskInternalServerError creates CreateRelabelNodesTaskInternalServerError with default headers values
func NewCreateRelabelNodesTaskInternalServerError() *CreateRelabelNodesTaskInternalServerError {

	return &CreateRelabelNodesTaskInternalServerError{}
}

// WriteResponse to the client
func (o *CreateRelabelNodesTaskInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
