// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetHealthStatusHandlerFunc turns a function with the right signature into a get health status handler
type GetHealthStatusHandlerFunc func(GetHealthStatusParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetHealthStatusHandlerFunc) Handle(params GetHealthStatusParams) middleware.Responder {
	return fn(params)
}

// GetHealthStatusHandler interface for that can handle valid get health status params
type GetHealthStatusHandler interface {
	Handle(GetHealthStatusParams) middleware.Responder
}

// NewGetHealthStatus creates a new http.Handler for the get health status operation
func NewGetHealthStatus(ctx *middleware.Context, handler GetHealthStatusHandler) *GetHealthStatus {
	return &GetHealthStatus{Context: ctx, Handler: handler}
}

/*GetHealthStatus swagger:route GET /api/v1.0/health/extended getHealthStatus

Get health status

*/
type GetHealthStatus struct {
	Context *middleware.Context
	Handler GetHealthStatusHandler
}

func (o *GetHealthStatus) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetHealthStatusParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
