// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetHealthStatusOKCode is the HTTP code returned for type GetHealthStatusOK
const GetHealthStatusOKCode int = 200

/*GetHealthStatusOK Generic String answer

swagger:response getHealthStatusOK
*/
type GetHealthStatusOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetHealthStatusOK creates GetHealthStatusOK with default headers values
func NewGetHealthStatusOK() *GetHealthStatusOK {

	return &GetHealthStatusOK{}
}

// WithPayload adds the payload to the get health status o k response
func (o *GetHealthStatusOK) WithPayload(payload string) *GetHealthStatusOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get health status o k response
func (o *GetHealthStatusOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetHealthStatusOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetHealthStatusUnauthorizedCode is the HTTP code returned for type GetHealthStatusUnauthorized
const GetHealthStatusUnauthorizedCode int = 401

/*GetHealthStatusUnauthorized 401 Not authorized

swagger:response getHealthStatusUnauthorized
*/
type GetHealthStatusUnauthorized struct {
}

// NewGetHealthStatusUnauthorized creates GetHealthStatusUnauthorized with default headers values
func NewGetHealthStatusUnauthorized() *GetHealthStatusUnauthorized {

	return &GetHealthStatusUnauthorized{}
}

// WriteResponse to the client
func (o *GetHealthStatusUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetHealthStatusForbiddenCode is the HTTP code returned for type GetHealthStatusForbidden
const GetHealthStatusForbiddenCode int = 403

/*GetHealthStatusForbidden 403 Forbidden

swagger:response getHealthStatusForbidden
*/
type GetHealthStatusForbidden struct {
}

// NewGetHealthStatusForbidden creates GetHealthStatusForbidden with default headers values
func NewGetHealthStatusForbidden() *GetHealthStatusForbidden {

	return &GetHealthStatusForbidden{}
}

// WriteResponse to the client
func (o *GetHealthStatusForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// GetHealthStatusInternalServerErrorCode is the HTTP code returned for type GetHealthStatusInternalServerError
const GetHealthStatusInternalServerErrorCode int = 500

/*GetHealthStatusInternalServerError 500 Internal Server Error

swagger:response getHealthStatusInternalServerError
*/
type GetHealthStatusInternalServerError struct {
}

// NewGetHealthStatusInternalServerError creates GetHealthStatusInternalServerError with default headers values
func NewGetHealthStatusInternalServerError() *GetHealthStatusInternalServerError {

	return &GetHealthStatusInternalServerError{}
}

// WriteResponse to the client
func (o *GetHealthStatusInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
