// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// LoadDesignDataOKCode is the HTTP code returned for type LoadDesignDataOK
const LoadDesignDataOKCode int = 200

/*LoadDesignDataOK Generic String answer

swagger:response loadDesignDataOK
*/
type LoadDesignDataOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewLoadDesignDataOK creates LoadDesignDataOK with default headers values
func NewLoadDesignDataOK() *LoadDesignDataOK {

	return &LoadDesignDataOK{}
}

// WithPayload adds the payload to the load design data o k response
func (o *LoadDesignDataOK) WithPayload(payload string) *LoadDesignDataOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the load design data o k response
func (o *LoadDesignDataOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LoadDesignDataOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// LoadDesignDataUnauthorizedCode is the HTTP code returned for type LoadDesignDataUnauthorized
const LoadDesignDataUnauthorizedCode int = 401

/*LoadDesignDataUnauthorized 401 Not authorized

swagger:response loadDesignDataUnauthorized
*/
type LoadDesignDataUnauthorized struct {
}

// NewLoadDesignDataUnauthorized creates LoadDesignDataUnauthorized with default headers values
func NewLoadDesignDataUnauthorized() *LoadDesignDataUnauthorized {

	return &LoadDesignDataUnauthorized{}
}

// WriteResponse to the client
func (o *LoadDesignDataUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// LoadDesignDataForbiddenCode is the HTTP code returned for type LoadDesignDataForbidden
const LoadDesignDataForbiddenCode int = 403

/*LoadDesignDataForbidden 403 Forbidden

swagger:response loadDesignDataForbidden
*/
type LoadDesignDataForbidden struct {
}

// NewLoadDesignDataForbidden creates LoadDesignDataForbidden with default headers values
func NewLoadDesignDataForbidden() *LoadDesignDataForbidden {

	return &LoadDesignDataForbidden{}
}

// WriteResponse to the client
func (o *LoadDesignDataForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// LoadDesignDataInternalServerErrorCode is the HTTP code returned for type LoadDesignDataInternalServerError
const LoadDesignDataInternalServerErrorCode int = 500

/*LoadDesignDataInternalServerError 500 Internal Server Error

swagger:response loadDesignDataInternalServerError
*/
type LoadDesignDataInternalServerError struct {
}

// NewLoadDesignDataInternalServerError creates LoadDesignDataInternalServerError with default headers values
func NewLoadDesignDataInternalServerError() *LoadDesignDataInternalServerError {

	return &LoadDesignDataInternalServerError{}
}

// WriteResponse to the client
func (o *LoadDesignDataInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
