// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetJoinScriptsParams creates a new GetJoinScriptsParams object
// with the default values initialized.
func NewGetJoinScriptsParams() *GetJoinScriptsParams {
	var ()
	return &GetJoinScriptsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetJoinScriptsParamsWithTimeout creates a new GetJoinScriptsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetJoinScriptsParamsWithTimeout(timeout time.Duration) *GetJoinScriptsParams {
	var ()
	return &GetJoinScriptsParams{

		timeout: timeout,
	}
}

// NewGetJoinScriptsParamsWithContext creates a new GetJoinScriptsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetJoinScriptsParamsWithContext(ctx context.Context) *GetJoinScriptsParams {
	var ()
	return &GetJoinScriptsParams{

		Context: ctx,
	}
}

// NewGetJoinScriptsParamsWithHTTPClient creates a new GetJoinScriptsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetJoinScriptsParamsWithHTTPClient(client *http.Client) *GetJoinScriptsParams {
	var ()
	return &GetJoinScriptsParams{
		HTTPClient: client,
	}
}

/*GetJoinScriptsParams contains all the parameters to send to the API endpoint
for the get join scripts operation typically these are written to a http.Request
*/
type GetJoinScriptsParams struct {

	/*XAuthToken
	  A fernet keystone bearer token used for authentication and authorization

	*/
	XAuthToken *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get join scripts params
func (o *GetJoinScriptsParams) WithTimeout(timeout time.Duration) *GetJoinScriptsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get join scripts params
func (o *GetJoinScriptsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get join scripts params
func (o *GetJoinScriptsParams) WithContext(ctx context.Context) *GetJoinScriptsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get join scripts params
func (o *GetJoinScriptsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get join scripts params
func (o *GetJoinScriptsParams) WithHTTPClient(client *http.Client) *GetJoinScriptsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get join scripts params
func (o *GetJoinScriptsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAuthToken adds the xAuthToken to the get join scripts params
func (o *GetJoinScriptsParams) WithXAuthToken(xAuthToken *string) *GetJoinScriptsParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the get join scripts params
func (o *GetJoinScriptsParams) SetXAuthToken(xAuthToken *string) {
	o.XAuthToken = xAuthToken
}

// WriteToRequest writes these params to a swagger request
func (o *GetJoinScriptsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XAuthToken != nil {

		// header param X-Auth-Token
		if err := r.SetHeaderParam("X-Auth-Token", *o.XAuthToken); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
