// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	errors "github.com/go-openapi/errors"
	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"

	models "github.com/kubekit99/airship-go-api/armada/models"
)

// GetReleasesHandlerFunc turns a function with the right signature into a get releases handler
type GetReleasesHandlerFunc func(GetReleasesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetReleasesHandlerFunc) Handle(params GetReleasesParams) middleware.Responder {
	return fn(params)
}

// GetReleasesHandler interface for that can handle valid get releases params
type GetReleasesHandler interface {
	Handle(GetReleasesParams) middleware.Responder
}

// NewGetReleases creates a new http.Handler for the get releases operation
func NewGetReleases(ctx *middleware.Context, handler GetReleasesHandler) *GetReleases {
	return &GetReleases{Context: ctx, Handler: handler}
}

/*GetReleases swagger:route GET /api/v1.0/releases getReleases

Returns list of Tiller releases

*/
type GetReleases struct {
	Context *middleware.Context
	Handler GetReleasesHandler
}

func (o *GetReleases) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetReleasesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetReleasesOKBody get releases o k body
// swagger:model GetReleasesOKBody
type GetReleasesOKBody struct {
	models.Releases
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *GetReleasesOKBody) UnmarshalJSON(raw []byte) error {
	// GetReleasesOKBodyAO0
	var getReleasesOKBodyAO0 models.Releases
	if err := swag.ReadJSON(raw, &getReleasesOKBodyAO0); err != nil {
		return err
	}
	o.Releases = getReleasesOKBodyAO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o GetReleasesOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	getReleasesOKBodyAO0, err := swag.WriteJSON(o.Releases)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, getReleasesOKBodyAO0)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this get releases o k body
func (o *GetReleasesOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Releases
	if err := o.Releases.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (o *GetReleasesOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetReleasesOKBody) UnmarshalBinary(b []byte) error {
	var res GetReleasesOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
