// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostValidateDesignOKCode is the HTTP code returned for type PostValidateDesignOK
const PostValidateDesignOKCode int = 200

/*PostValidateDesignOK Response of a validation check

swagger:response postValidateDesignOK
*/
type PostValidateDesignOK struct {

	/*
	  In: Body
	*/
	Payload *PostValidateDesignOKBody `json:"body,omitempty"`
}

// NewPostValidateDesignOK creates PostValidateDesignOK with default headers values
func NewPostValidateDesignOK() *PostValidateDesignOK {

	return &PostValidateDesignOK{}
}

// WithPayload adds the payload to the post validate design o k response
func (o *PostValidateDesignOK) WithPayload(payload *PostValidateDesignOKBody) *PostValidateDesignOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post validate design o k response
func (o *PostValidateDesignOK) SetPayload(payload *PostValidateDesignOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostValidateDesignOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostValidateDesignBadRequestCode is the HTTP code returned for type PostValidateDesignBadRequest
const PostValidateDesignBadRequestCode int = 400

/*PostValidateDesignBadRequest 400 Bad request

swagger:response postValidateDesignBadRequest
*/
type PostValidateDesignBadRequest struct {
}

// NewPostValidateDesignBadRequest creates PostValidateDesignBadRequest with default headers values
func NewPostValidateDesignBadRequest() *PostValidateDesignBadRequest {

	return &PostValidateDesignBadRequest{}
}

// WriteResponse to the client
func (o *PostValidateDesignBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostValidateDesignUnauthorizedCode is the HTTP code returned for type PostValidateDesignUnauthorized
const PostValidateDesignUnauthorizedCode int = 401

/*PostValidateDesignUnauthorized 401 Not authorized

swagger:response postValidateDesignUnauthorized
*/
type PostValidateDesignUnauthorized struct {
}

// NewPostValidateDesignUnauthorized creates PostValidateDesignUnauthorized with default headers values
func NewPostValidateDesignUnauthorized() *PostValidateDesignUnauthorized {

	return &PostValidateDesignUnauthorized{}
}

// WriteResponse to the client
func (o *PostValidateDesignUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// PostValidateDesignForbiddenCode is the HTTP code returned for type PostValidateDesignForbidden
const PostValidateDesignForbiddenCode int = 403

/*PostValidateDesignForbidden 403 Forbidden

swagger:response postValidateDesignForbidden
*/
type PostValidateDesignForbidden struct {
}

// NewPostValidateDesignForbidden creates PostValidateDesignForbidden with default headers values
func NewPostValidateDesignForbidden() *PostValidateDesignForbidden {

	return &PostValidateDesignForbidden{}
}

// WriteResponse to the client
func (o *PostValidateDesignForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
