// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostTestReleaseNameParams creates a new PostTestReleaseNameParams object
// with the default values initialized.
func NewPostTestReleaseNameParams() PostTestReleaseNameParams {

	var (
		// initialize parameters with default values

		tillerHostDefault = string("None")
	)

	return PostTestReleaseNameParams{
		TillerHost: &tillerHostDefault,
	}
}

// PostTestReleaseNameParams contains all the bound params for the post test release name operation
// typically these are obtained from a http.Request
//
// swagger:parameters postTestReleaseName
type PostTestReleaseNameParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*A fernet keystone bearer token used for authentication and authorization
	  In: header
	*/
	XAuthToken *string
	/*Name of the release to be tested
	  Required: true
	  In: path
	*/
	ReleaseName string
	/*Hostname of the Tiller server
	  In: query
	  Default: "None"
	*/
	TillerHost *string
	/*Tiller namespace. Default is the value of `CONF.tiller_namespace`
	  In: query
	*/
	TillerNamespace *string
	/*Port number of the Tiller server. Default is the value of `CONF.tiller_port`.
	  In: query
	*/
	TillerPort *int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostTestReleaseNameParams() beforehand.
func (o *PostTestReleaseNameParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	if err := o.bindXAuthToken(r.Header[http.CanonicalHeaderKey("X-Auth-Token")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	rReleaseName, rhkReleaseName, _ := route.Params.GetOK("release_name")
	if err := o.bindReleaseName(rReleaseName, rhkReleaseName, route.Formats); err != nil {
		res = append(res, err)
	}

	qTillerHost, qhkTillerHost, _ := qs.GetOK("tiller_host")
	if err := o.bindTillerHost(qTillerHost, qhkTillerHost, route.Formats); err != nil {
		res = append(res, err)
	}

	qTillerNamespace, qhkTillerNamespace, _ := qs.GetOK("tiller_namespace")
	if err := o.bindTillerNamespace(qTillerNamespace, qhkTillerNamespace, route.Formats); err != nil {
		res = append(res, err)
	}

	qTillerPort, qhkTillerPort, _ := qs.GetOK("tiller_port")
	if err := o.bindTillerPort(qTillerPort, qhkTillerPort, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindXAuthToken binds and validates parameter XAuthToken from header.
func (o *PostTestReleaseNameParams) bindXAuthToken(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.XAuthToken = &raw

	return nil
}

// bindReleaseName binds and validates parameter ReleaseName from path.
func (o *PostTestReleaseNameParams) bindReleaseName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.ReleaseName = raw

	return nil
}

// bindTillerHost binds and validates parameter TillerHost from query.
func (o *PostTestReleaseNameParams) bindTillerHost(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewPostTestReleaseNameParams()
		return nil
	}

	o.TillerHost = &raw

	return nil
}

// bindTillerNamespace binds and validates parameter TillerNamespace from query.
func (o *PostTestReleaseNameParams) bindTillerNamespace(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.TillerNamespace = &raw

	return nil
}

// bindTillerPort binds and validates parameter TillerPort from query.
func (o *PostTestReleaseNameParams) bindTillerPort(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("tiller_port", "query", "int64", raw)
	}
	o.TillerPort = &value

	return nil
}
