// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostTestsOKCode is the HTTP code returned for type PostTestsOK
const PostTestsOKCode int = 200

/*PostTestsOK Response of all tests

swagger:response postTestsOK
*/
type PostTestsOK struct {

	/*
	  In: Body
	*/
	Payload *PostTestsOKBody `json:"body,omitempty"`
}

// NewPostTestsOK creates PostTestsOK with default headers values
func NewPostTestsOK() *PostTestsOK {

	return &PostTestsOK{}
}

// WithPayload adds the payload to the post tests o k response
func (o *PostTestsOK) WithPayload(payload *PostTestsOKBody) *PostTestsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post tests o k response
func (o *PostTestsOK) SetPayload(payload *PostTestsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostTestsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostTestsBadRequestCode is the HTTP code returned for type PostTestsBadRequest
const PostTestsBadRequestCode int = 400

/*PostTestsBadRequest 400 Bad request

swagger:response postTestsBadRequest
*/
type PostTestsBadRequest struct {
}

// NewPostTestsBadRequest creates PostTestsBadRequest with default headers values
func NewPostTestsBadRequest() *PostTestsBadRequest {

	return &PostTestsBadRequest{}
}

// WriteResponse to the client
func (o *PostTestsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostTestsUnauthorizedCode is the HTTP code returned for type PostTestsUnauthorized
const PostTestsUnauthorizedCode int = 401

/*PostTestsUnauthorized 401 Not authorized

swagger:response postTestsUnauthorized
*/
type PostTestsUnauthorized struct {
}

// NewPostTestsUnauthorized creates PostTestsUnauthorized with default headers values
func NewPostTestsUnauthorized() *PostTestsUnauthorized {

	return &PostTestsUnauthorized{}
}

// WriteResponse to the client
func (o *PostTestsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// PostTestsForbiddenCode is the HTTP code returned for type PostTestsForbidden
const PostTestsForbiddenCode int = 403

/*PostTestsForbidden 403 Forbidden

swagger:response postTestsForbidden
*/
type PostTestsForbidden struct {
}

// NewPostTestsForbidden creates PostTestsForbidden with default headers values
func NewPostTestsForbidden() *PostTestsForbidden {

	return &PostTestsForbidden{}
}

// WriteResponse to the client
func (o *PostTestsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// PostTestsInternalServerErrorCode is the HTTP code returned for type PostTestsInternalServerError
const PostTestsInternalServerErrorCode int = 500

/*PostTestsInternalServerError 500 Internal Server Error

swagger:response postTestsInternalServerError
*/
type PostTestsInternalServerError struct {
}

// NewPostTestsInternalServerError creates PostTestsInternalServerError with default headers values
func NewPostTestsInternalServerError() *PostTestsInternalServerError {

	return &PostTestsInternalServerError{}
}

// WriteResponse to the client
func (o *PostTestsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
