// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetActionByActionIDReader is a Reader for the GetActionByActionID structure.
type GetActionByActionIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetActionByActionIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetActionByActionIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetActionByActionIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetActionByActionIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetActionByActionIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetActionByActionIDOK creates a GetActionByActionIDOK with default headers values
func NewGetActionByActionIDOK() *GetActionByActionIDOK {
	return &GetActionByActionIDOK{}
}

/*GetActionByActionIDOK handles this case with default header values.

Generic String answer
*/
type GetActionByActionIDOK struct {
	Payload string
}

func (o *GetActionByActionIDOK) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/actions/{action-id}][%d] getActionByActionIdOK  %+v", 200, o.Payload)
}

func (o *GetActionByActionIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetActionByActionIDUnauthorized creates a GetActionByActionIDUnauthorized with default headers values
func NewGetActionByActionIDUnauthorized() *GetActionByActionIDUnauthorized {
	return &GetActionByActionIDUnauthorized{}
}

/*GetActionByActionIDUnauthorized handles this case with default header values.

401 Not authorized
*/
type GetActionByActionIDUnauthorized struct {
}

func (o *GetActionByActionIDUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/actions/{action-id}][%d] getActionByActionIdUnauthorized ", 401)
}

func (o *GetActionByActionIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetActionByActionIDForbidden creates a GetActionByActionIDForbidden with default headers values
func NewGetActionByActionIDForbidden() *GetActionByActionIDForbidden {
	return &GetActionByActionIDForbidden{}
}

/*GetActionByActionIDForbidden handles this case with default header values.

403 Forbidden
*/
type GetActionByActionIDForbidden struct {
}

func (o *GetActionByActionIDForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/actions/{action-id}][%d] getActionByActionIdForbidden ", 403)
}

func (o *GetActionByActionIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetActionByActionIDInternalServerError creates a GetActionByActionIDInternalServerError with default headers values
func NewGetActionByActionIDInternalServerError() *GetActionByActionIDInternalServerError {
	return &GetActionByActionIDInternalServerError{}
}

/*GetActionByActionIDInternalServerError handles this case with default header values.

500 Internal Server Error
*/
type GetActionByActionIDInternalServerError struct {
}

func (o *GetActionByActionIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/actions/{action-id}][%d] getActionByActionIdInternalServerError ", 500)
}

func (o *GetActionByActionIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
