// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetRenderedConfigDocsReader is a Reader for the GetRenderedConfigDocs structure.
type GetRenderedConfigDocsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRenderedConfigDocsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetRenderedConfigDocsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetRenderedConfigDocsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetRenderedConfigDocsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetRenderedConfigDocsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetRenderedConfigDocsOK creates a GetRenderedConfigDocsOK with default headers values
func NewGetRenderedConfigDocsOK() *GetRenderedConfigDocsOK {
	return &GetRenderedConfigDocsOK{}
}

/*GetRenderedConfigDocsOK handles this case with default header values.

Generic String answer
*/
type GetRenderedConfigDocsOK struct {
	Payload string
}

func (o *GetRenderedConfigDocsOK) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/renderedconfigdocs][%d] getRenderedConfigDocsOK  %+v", 200, o.Payload)
}

func (o *GetRenderedConfigDocsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRenderedConfigDocsUnauthorized creates a GetRenderedConfigDocsUnauthorized with default headers values
func NewGetRenderedConfigDocsUnauthorized() *GetRenderedConfigDocsUnauthorized {
	return &GetRenderedConfigDocsUnauthorized{}
}

/*GetRenderedConfigDocsUnauthorized handles this case with default header values.

401 Not authorized
*/
type GetRenderedConfigDocsUnauthorized struct {
}

func (o *GetRenderedConfigDocsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/renderedconfigdocs][%d] getRenderedConfigDocsUnauthorized ", 401)
}

func (o *GetRenderedConfigDocsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetRenderedConfigDocsForbidden creates a GetRenderedConfigDocsForbidden with default headers values
func NewGetRenderedConfigDocsForbidden() *GetRenderedConfigDocsForbidden {
	return &GetRenderedConfigDocsForbidden{}
}

/*GetRenderedConfigDocsForbidden handles this case with default header values.

403 Forbidden
*/
type GetRenderedConfigDocsForbidden struct {
}

func (o *GetRenderedConfigDocsForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/renderedconfigdocs][%d] getRenderedConfigDocsForbidden ", 403)
}

func (o *GetRenderedConfigDocsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetRenderedConfigDocsInternalServerError creates a GetRenderedConfigDocsInternalServerError with default headers values
func NewGetRenderedConfigDocsInternalServerError() *GetRenderedConfigDocsInternalServerError {
	return &GetRenderedConfigDocsInternalServerError{}
}

/*GetRenderedConfigDocsInternalServerError handles this case with default header values.

500 Internal Server Error
*/
type GetRenderedConfigDocsInternalServerError struct {
}

func (o *GetRenderedConfigDocsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/renderedconfigdocs][%d] getRenderedConfigDocsInternalServerError ", 500)
}

func (o *GetRenderedConfigDocsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
