// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetConfigDocByIDReader is a Reader for the GetConfigDocByID structure.
type GetConfigDocByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetConfigDocByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetConfigDocByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetConfigDocByIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetConfigDocByIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetConfigDocByIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetConfigDocByIDOK creates a GetConfigDocByIDOK with default headers values
func NewGetConfigDocByIDOK() *GetConfigDocByIDOK {
	return &GetConfigDocByIDOK{}
}

/*GetConfigDocByIDOK handles this case with default header values.

Generic String answer
*/
type GetConfigDocByIDOK struct {
	Payload string
}

func (o *GetConfigDocByIDOK) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/configdocs/{collection-id}][%d] getConfigDocByIdOK  %+v", 200, o.Payload)
}

func (o *GetConfigDocByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetConfigDocByIDUnauthorized creates a GetConfigDocByIDUnauthorized with default headers values
func NewGetConfigDocByIDUnauthorized() *GetConfigDocByIDUnauthorized {
	return &GetConfigDocByIDUnauthorized{}
}

/*GetConfigDocByIDUnauthorized handles this case with default header values.

401 Not authorized
*/
type GetConfigDocByIDUnauthorized struct {
}

func (o *GetConfigDocByIDUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/configdocs/{collection-id}][%d] getConfigDocByIdUnauthorized ", 401)
}

func (o *GetConfigDocByIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetConfigDocByIDForbidden creates a GetConfigDocByIDForbidden with default headers values
func NewGetConfigDocByIDForbidden() *GetConfigDocByIDForbidden {
	return &GetConfigDocByIDForbidden{}
}

/*GetConfigDocByIDForbidden handles this case with default header values.

403 Forbidden
*/
type GetConfigDocByIDForbidden struct {
}

func (o *GetConfigDocByIDForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/configdocs/{collection-id}][%d] getConfigDocByIdForbidden ", 403)
}

func (o *GetConfigDocByIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetConfigDocByIDInternalServerError creates a GetConfigDocByIDInternalServerError with default headers values
func NewGetConfigDocByIDInternalServerError() *GetConfigDocByIDInternalServerError {
	return &GetConfigDocByIDInternalServerError{}
}

/*GetConfigDocByIDInternalServerError handles this case with default header values.

500 Internal Server Error
*/
type GetConfigDocByIDInternalServerError struct {
}

func (o *GetConfigDocByIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/configdocs/{collection-id}][%d] getConfigDocByIdInternalServerError ", 500)
}

func (o *GetConfigDocByIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
