// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetWFActionStepLogsByIDParams creates a new GetWFActionStepLogsByIDParams object
// with the default values initialized.
func NewGetWFActionStepLogsByIDParams() *GetWFActionStepLogsByIDParams {
	var ()
	return &GetWFActionStepLogsByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetWFActionStepLogsByIDParamsWithTimeout creates a new GetWFActionStepLogsByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetWFActionStepLogsByIDParamsWithTimeout(timeout time.Duration) *GetWFActionStepLogsByIDParams {
	var ()
	return &GetWFActionStepLogsByIDParams{

		timeout: timeout,
	}
}

// NewGetWFActionStepLogsByIDParamsWithContext creates a new GetWFActionStepLogsByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetWFActionStepLogsByIDParamsWithContext(ctx context.Context) *GetWFActionStepLogsByIDParams {
	var ()
	return &GetWFActionStepLogsByIDParams{

		Context: ctx,
	}
}

// NewGetWFActionStepLogsByIDParamsWithHTTPClient creates a new GetWFActionStepLogsByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetWFActionStepLogsByIDParamsWithHTTPClient(client *http.Client) *GetWFActionStepLogsByIDParams {
	var ()
	return &GetWFActionStepLogsByIDParams{
		HTTPClient: client,
	}
}

/*GetWFActionStepLogsByIDParams contains all the parameters to send to the API endpoint
for the get w f action step logs by Id operation typically these are written to a http.Request
*/
type GetWFActionStepLogsByIDParams struct {

	/*XAuthToken
	  A fernet keystone bearer token used for authentication and authorization

	*/
	XAuthToken *string
	/*ActionID*/
	ActionID string
	/*StepID*/
	StepID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get w f action step logs by Id params
func (o *GetWFActionStepLogsByIDParams) WithTimeout(timeout time.Duration) *GetWFActionStepLogsByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get w f action step logs by Id params
func (o *GetWFActionStepLogsByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get w f action step logs by Id params
func (o *GetWFActionStepLogsByIDParams) WithContext(ctx context.Context) *GetWFActionStepLogsByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get w f action step logs by Id params
func (o *GetWFActionStepLogsByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get w f action step logs by Id params
func (o *GetWFActionStepLogsByIDParams) WithHTTPClient(client *http.Client) *GetWFActionStepLogsByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get w f action step logs by Id params
func (o *GetWFActionStepLogsByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAuthToken adds the xAuthToken to the get w f action step logs by Id params
func (o *GetWFActionStepLogsByIDParams) WithXAuthToken(xAuthToken *string) *GetWFActionStepLogsByIDParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the get w f action step logs by Id params
func (o *GetWFActionStepLogsByIDParams) SetXAuthToken(xAuthToken *string) {
	o.XAuthToken = xAuthToken
}

// WithActionID adds the actionID to the get w f action step logs by Id params
func (o *GetWFActionStepLogsByIDParams) WithActionID(actionID string) *GetWFActionStepLogsByIDParams {
	o.SetActionID(actionID)
	return o
}

// SetActionID adds the actionId to the get w f action step logs by Id params
func (o *GetWFActionStepLogsByIDParams) SetActionID(actionID string) {
	o.ActionID = actionID
}

// WithStepID adds the stepID to the get w f action step logs by Id params
func (o *GetWFActionStepLogsByIDParams) WithStepID(stepID string) *GetWFActionStepLogsByIDParams {
	o.SetStepID(stepID)
	return o
}

// SetStepID adds the stepId to the get w f action step logs by Id params
func (o *GetWFActionStepLogsByIDParams) SetStepID(stepID string) {
	o.StepID = stepID
}

// WriteToRequest writes these params to a swagger request
func (o *GetWFActionStepLogsByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XAuthToken != nil {

		// header param X-Auth-Token
		if err := r.SetHeaderParam("X-Auth-Token", *o.XAuthToken); err != nil {
			return err
		}

	}

	// path param action-id
	if err := r.SetPathParam("action-id", o.ActionID); err != nil {
		return err
	}

	// path param step-id
	if err := r.SetPathParam("step-id", o.StepID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
