// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetActionValidationByIDParams creates a new GetActionValidationByIDParams object
// with the default values initialized.
func NewGetActionValidationByIDParams() *GetActionValidationByIDParams {
	var ()
	return &GetActionValidationByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetActionValidationByIDParamsWithTimeout creates a new GetActionValidationByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetActionValidationByIDParamsWithTimeout(timeout time.Duration) *GetActionValidationByIDParams {
	var ()
	return &GetActionValidationByIDParams{

		timeout: timeout,
	}
}

// NewGetActionValidationByIDParamsWithContext creates a new GetActionValidationByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetActionValidationByIDParamsWithContext(ctx context.Context) *GetActionValidationByIDParams {
	var ()
	return &GetActionValidationByIDParams{

		Context: ctx,
	}
}

// NewGetActionValidationByIDParamsWithHTTPClient creates a new GetActionValidationByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetActionValidationByIDParamsWithHTTPClient(client *http.Client) *GetActionValidationByIDParams {
	var ()
	return &GetActionValidationByIDParams{
		HTTPClient: client,
	}
}

/*GetActionValidationByIDParams contains all the parameters to send to the API endpoint
for the get action validation by Id operation typically these are written to a http.Request
*/
type GetActionValidationByIDParams struct {

	/*XAuthToken
	  A fernet keystone bearer token used for authentication and authorization

	*/
	XAuthToken *string
	/*ActionID*/
	ActionID string
	/*ValidationID*/
	ValidationID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get action validation by Id params
func (o *GetActionValidationByIDParams) WithTimeout(timeout time.Duration) *GetActionValidationByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get action validation by Id params
func (o *GetActionValidationByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get action validation by Id params
func (o *GetActionValidationByIDParams) WithContext(ctx context.Context) *GetActionValidationByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get action validation by Id params
func (o *GetActionValidationByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get action validation by Id params
func (o *GetActionValidationByIDParams) WithHTTPClient(client *http.Client) *GetActionValidationByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get action validation by Id params
func (o *GetActionValidationByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAuthToken adds the xAuthToken to the get action validation by Id params
func (o *GetActionValidationByIDParams) WithXAuthToken(xAuthToken *string) *GetActionValidationByIDParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the get action validation by Id params
func (o *GetActionValidationByIDParams) SetXAuthToken(xAuthToken *string) {
	o.XAuthToken = xAuthToken
}

// WithActionID adds the actionID to the get action validation by Id params
func (o *GetActionValidationByIDParams) WithActionID(actionID string) *GetActionValidationByIDParams {
	o.SetActionID(actionID)
	return o
}

// SetActionID adds the actionId to the get action validation by Id params
func (o *GetActionValidationByIDParams) SetActionID(actionID string) {
	o.ActionID = actionID
}

// WithValidationID adds the validationID to the get action validation by Id params
func (o *GetActionValidationByIDParams) WithValidationID(validationID string) *GetActionValidationByIDParams {
	o.SetValidationID(validationID)
	return o
}

// SetValidationID adds the validationId to the get action validation by Id params
func (o *GetActionValidationByIDParams) SetValidationID(validationID string) {
	o.ValidationID = validationID
}

// WriteToRequest writes these params to a swagger request
func (o *GetActionValidationByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XAuthToken != nil {

		// header param X-Auth-Token
		if err := r.SetHeaderParam("X-Auth-Token", *o.XAuthToken); err != nil {
			return err
		}

	}

	// path param action-id
	if err := r.SetPathParam("action-id", o.ActionID); err != nil {
		return err
	}

	// path param validation-id
	if err := r.SetPathParam("validation-id", o.ValidationID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
