// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetActionByActionIDParams creates a new GetActionByActionIDParams object
// with the default values initialized.
func NewGetActionByActionIDParams() *GetActionByActionIDParams {
	var ()
	return &GetActionByActionIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetActionByActionIDParamsWithTimeout creates a new GetActionByActionIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetActionByActionIDParamsWithTimeout(timeout time.Duration) *GetActionByActionIDParams {
	var ()
	return &GetActionByActionIDParams{

		timeout: timeout,
	}
}

// NewGetActionByActionIDParamsWithContext creates a new GetActionByActionIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetActionByActionIDParamsWithContext(ctx context.Context) *GetActionByActionIDParams {
	var ()
	return &GetActionByActionIDParams{

		Context: ctx,
	}
}

// NewGetActionByActionIDParamsWithHTTPClient creates a new GetActionByActionIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetActionByActionIDParamsWithHTTPClient(client *http.Client) *GetActionByActionIDParams {
	var ()
	return &GetActionByActionIDParams{
		HTTPClient: client,
	}
}

/*GetActionByActionIDParams contains all the parameters to send to the API endpoint
for the get action by action Id operation typically these are written to a http.Request
*/
type GetActionByActionIDParams struct {

	/*XAuthToken
	  A fernet keystone bearer token used for authentication and authorization

	*/
	XAuthToken *string
	/*ActionID*/
	ActionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get action by action Id params
func (o *GetActionByActionIDParams) WithTimeout(timeout time.Duration) *GetActionByActionIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get action by action Id params
func (o *GetActionByActionIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get action by action Id params
func (o *GetActionByActionIDParams) WithContext(ctx context.Context) *GetActionByActionIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get action by action Id params
func (o *GetActionByActionIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get action by action Id params
func (o *GetActionByActionIDParams) WithHTTPClient(client *http.Client) *GetActionByActionIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get action by action Id params
func (o *GetActionByActionIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAuthToken adds the xAuthToken to the get action by action Id params
func (o *GetActionByActionIDParams) WithXAuthToken(xAuthToken *string) *GetActionByActionIDParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the get action by action Id params
func (o *GetActionByActionIDParams) SetXAuthToken(xAuthToken *string) {
	o.XAuthToken = xAuthToken
}

// WithActionID adds the actionID to the get action by action Id params
func (o *GetActionByActionIDParams) WithActionID(actionID string) *GetActionByActionIDParams {
	o.SetActionID(actionID)
	return o
}

// SetActionID adds the actionId to the get action by action Id params
func (o *GetActionByActionIDParams) SetActionID(actionID string) {
	o.ActionID = actionID
}

// WriteToRequest writes these params to a swagger request
func (o *GetActionByActionIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XAuthToken != nil {

		// header param X-Auth-Token
		if err := r.SetHeaderParam("X-Auth-Token", *o.XAuthToken); err != nil {
			return err
		}

	}

	// path param action-id
	if err := r.SetPathParam("action-id", o.ActionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
