// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostApplyManifestParams creates a new PostApplyManifestParams object
// with the default values initialized.
func NewPostApplyManifestParams() *PostApplyManifestParams {
	var ()
	return &PostApplyManifestParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostApplyManifestParamsWithTimeout creates a new PostApplyManifestParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostApplyManifestParamsWithTimeout(timeout time.Duration) *PostApplyManifestParams {
	var ()
	return &PostApplyManifestParams{

		timeout: timeout,
	}
}

// NewPostApplyManifestParamsWithContext creates a new PostApplyManifestParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostApplyManifestParamsWithContext(ctx context.Context) *PostApplyManifestParams {
	var ()
	return &PostApplyManifestParams{

		Context: ctx,
	}
}

// NewPostApplyManifestParamsWithHTTPClient creates a new PostApplyManifestParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostApplyManifestParamsWithHTTPClient(client *http.Client) *PostApplyManifestParams {
	var ()
	return &PostApplyManifestParams{
		HTTPClient: client,
	}
}

/*PostApplyManifestParams contains all the parameters to send to the API endpoint
for the post apply manifest operation typically these are written to a http.Request
*/
type PostApplyManifestParams struct {

	/*ContentType*/
	ContentType string
	/*XAuthToken
	  A fernet keystone bearer token used for authentication and authorization

	*/
	XAuthToken *string
	/*RequestBody
	  Body containing the manifest hrefs JSON or YAML and a set of overrides

	*/
	RequestBody PostApplyManifestBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post apply manifest params
func (o *PostApplyManifestParams) WithTimeout(timeout time.Duration) *PostApplyManifestParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post apply manifest params
func (o *PostApplyManifestParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post apply manifest params
func (o *PostApplyManifestParams) WithContext(ctx context.Context) *PostApplyManifestParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post apply manifest params
func (o *PostApplyManifestParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post apply manifest params
func (o *PostApplyManifestParams) WithHTTPClient(client *http.Client) *PostApplyManifestParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post apply manifest params
func (o *PostApplyManifestParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContentType adds the contentType to the post apply manifest params
func (o *PostApplyManifestParams) WithContentType(contentType string) *PostApplyManifestParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the post apply manifest params
func (o *PostApplyManifestParams) SetContentType(contentType string) {
	o.ContentType = contentType
}

// WithXAuthToken adds the xAuthToken to the post apply manifest params
func (o *PostApplyManifestParams) WithXAuthToken(xAuthToken *string) *PostApplyManifestParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the post apply manifest params
func (o *PostApplyManifestParams) SetXAuthToken(xAuthToken *string) {
	o.XAuthToken = xAuthToken
}

// WithRequestBody adds the requestBody to the post apply manifest params
func (o *PostApplyManifestParams) WithRequestBody(requestBody PostApplyManifestBody) *PostApplyManifestParams {
	o.SetRequestBody(requestBody)
	return o
}

// SetRequestBody adds the requestBody to the post apply manifest params
func (o *PostApplyManifestParams) SetRequestBody(requestBody PostApplyManifestBody) {
	o.RequestBody = requestBody
}

// WriteToRequest writes these params to a swagger request
func (o *PostApplyManifestParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Content-Type
	if err := r.SetHeaderParam("Content-Type", o.ContentType); err != nil {
		return err
	}

	if o.XAuthToken != nil {

		// header param X-Auth-Token
		if err := r.SetHeaderParam("X-Auth-Token", *o.XAuthToken); err != nil {
			return err
		}

	}

	if err := r.SetBodyParam(o.RequestBody); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
