// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewRetrieveConfigDocsClearTextByCollectionIDParams creates a new RetrieveConfigDocsClearTextByCollectionIDParams object
// with the default values initialized.
func NewRetrieveConfigDocsClearTextByCollectionIDParams() *RetrieveConfigDocsClearTextByCollectionIDParams {
	var ()
	return &RetrieveConfigDocsClearTextByCollectionIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRetrieveConfigDocsClearTextByCollectionIDParamsWithTimeout creates a new RetrieveConfigDocsClearTextByCollectionIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRetrieveConfigDocsClearTextByCollectionIDParamsWithTimeout(timeout time.Duration) *RetrieveConfigDocsClearTextByCollectionIDParams {
	var ()
	return &RetrieveConfigDocsClearTextByCollectionIDParams{

		timeout: timeout,
	}
}

// NewRetrieveConfigDocsClearTextByCollectionIDParamsWithContext creates a new RetrieveConfigDocsClearTextByCollectionIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewRetrieveConfigDocsClearTextByCollectionIDParamsWithContext(ctx context.Context) *RetrieveConfigDocsClearTextByCollectionIDParams {
	var ()
	return &RetrieveConfigDocsClearTextByCollectionIDParams{

		Context: ctx,
	}
}

// NewRetrieveConfigDocsClearTextByCollectionIDParamsWithHTTPClient creates a new RetrieveConfigDocsClearTextByCollectionIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRetrieveConfigDocsClearTextByCollectionIDParamsWithHTTPClient(client *http.Client) *RetrieveConfigDocsClearTextByCollectionIDParams {
	var ()
	return &RetrieveConfigDocsClearTextByCollectionIDParams{
		HTTPClient: client,
	}
}

/*RetrieveConfigDocsClearTextByCollectionIDParams contains all the parameters to send to the API endpoint
for the retrieve config docs clear text by collection Id operation typically these are written to a http.Request
*/
type RetrieveConfigDocsClearTextByCollectionIDParams struct {

	/*XAuthToken
	  A fernet keystone bearer token used for authentication and authorization

	*/
	XAuthToken *string
	/*CollectionID*/
	CollectionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the retrieve config docs clear text by collection Id params
func (o *RetrieveConfigDocsClearTextByCollectionIDParams) WithTimeout(timeout time.Duration) *RetrieveConfigDocsClearTextByCollectionIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the retrieve config docs clear text by collection Id params
func (o *RetrieveConfigDocsClearTextByCollectionIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the retrieve config docs clear text by collection Id params
func (o *RetrieveConfigDocsClearTextByCollectionIDParams) WithContext(ctx context.Context) *RetrieveConfigDocsClearTextByCollectionIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the retrieve config docs clear text by collection Id params
func (o *RetrieveConfigDocsClearTextByCollectionIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the retrieve config docs clear text by collection Id params
func (o *RetrieveConfigDocsClearTextByCollectionIDParams) WithHTTPClient(client *http.Client) *RetrieveConfigDocsClearTextByCollectionIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the retrieve config docs clear text by collection Id params
func (o *RetrieveConfigDocsClearTextByCollectionIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAuthToken adds the xAuthToken to the retrieve config docs clear text by collection Id params
func (o *RetrieveConfigDocsClearTextByCollectionIDParams) WithXAuthToken(xAuthToken *string) *RetrieveConfigDocsClearTextByCollectionIDParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the retrieve config docs clear text by collection Id params
func (o *RetrieveConfigDocsClearTextByCollectionIDParams) SetXAuthToken(xAuthToken *string) {
	o.XAuthToken = xAuthToken
}

// WithCollectionID adds the collectionID to the retrieve config docs clear text by collection Id params
func (o *RetrieveConfigDocsClearTextByCollectionIDParams) WithCollectionID(collectionID string) *RetrieveConfigDocsClearTextByCollectionIDParams {
	o.SetCollectionID(collectionID)
	return o
}

// SetCollectionID adds the collectionId to the retrieve config docs clear text by collection Id params
func (o *RetrieveConfigDocsClearTextByCollectionIDParams) SetCollectionID(collectionID string) {
	o.CollectionID = collectionID
}

// WriteToRequest writes these params to a swagger request
func (o *RetrieveConfigDocsClearTextByCollectionIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XAuthToken != nil {

		// header param X-Auth-Token
		if err := r.SetHeaderParam("X-Auth-Token", *o.XAuthToken); err != nil {
			return err
		}

	}

	// path param collection-id
	if err := r.SetPathParam("collection-id", o.CollectionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
