// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostTestsParams creates a new PostTestsParams object
// with the default values initialized.
func NewPostTestsParams() *PostTestsParams {
	var (
		tillerHostDefault = string("None")
	)
	return &PostTestsParams{
		TillerHost: &tillerHostDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewPostTestsParamsWithTimeout creates a new PostTestsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostTestsParamsWithTimeout(timeout time.Duration) *PostTestsParams {
	var (
		tillerHostDefault = string("None")
	)
	return &PostTestsParams{
		TillerHost: &tillerHostDefault,

		timeout: timeout,
	}
}

// NewPostTestsParamsWithContext creates a new PostTestsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostTestsParamsWithContext(ctx context.Context) *PostTestsParams {
	var (
		tillerHostDefault = string("None")
	)
	return &PostTestsParams{
		TillerHost: &tillerHostDefault,

		Context: ctx,
	}
}

// NewPostTestsParamsWithHTTPClient creates a new PostTestsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostTestsParamsWithHTTPClient(client *http.Client) *PostTestsParams {
	var (
		tillerHostDefault = string("None")
	)
	return &PostTestsParams{
		TillerHost: &tillerHostDefault,
		HTTPClient: client,
	}
}

/*PostTestsParams contains all the parameters to send to the API endpoint
for the post tests operation typically these are written to a http.Request
*/
type PostTestsParams struct {

	/*XAuthToken
	  A fernet keystone bearer token used for authentication and authorization

	*/
	XAuthToken *string
	/*RequestBody
	  JSON or YAML representation of the manifest being processed.

	*/
	RequestBody interface{}
	/*TargetManifest
	  Specifies the manifest to target if there are multiples.

	*/
	TargetManifest *string
	/*TillerHost
	  Hostname of the Tiller server

	*/
	TillerHost *string
	/*TillerNamespace
	  Tiller namespace. Default is the value of `CONF.tiller_namespace`

	*/
	TillerNamespace *string
	/*TillerPort
	  Port number of the Tiller server. Default is the value of `CONF.tiller_port`.

	*/
	TillerPort *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post tests params
func (o *PostTestsParams) WithTimeout(timeout time.Duration) *PostTestsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post tests params
func (o *PostTestsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post tests params
func (o *PostTestsParams) WithContext(ctx context.Context) *PostTestsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post tests params
func (o *PostTestsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post tests params
func (o *PostTestsParams) WithHTTPClient(client *http.Client) *PostTestsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post tests params
func (o *PostTestsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAuthToken adds the xAuthToken to the post tests params
func (o *PostTestsParams) WithXAuthToken(xAuthToken *string) *PostTestsParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the post tests params
func (o *PostTestsParams) SetXAuthToken(xAuthToken *string) {
	o.XAuthToken = xAuthToken
}

// WithRequestBody adds the requestBody to the post tests params
func (o *PostTestsParams) WithRequestBody(requestBody interface{}) *PostTestsParams {
	o.SetRequestBody(requestBody)
	return o
}

// SetRequestBody adds the requestBody to the post tests params
func (o *PostTestsParams) SetRequestBody(requestBody interface{}) {
	o.RequestBody = requestBody
}

// WithTargetManifest adds the targetManifest to the post tests params
func (o *PostTestsParams) WithTargetManifest(targetManifest *string) *PostTestsParams {
	o.SetTargetManifest(targetManifest)
	return o
}

// SetTargetManifest adds the targetManifest to the post tests params
func (o *PostTestsParams) SetTargetManifest(targetManifest *string) {
	o.TargetManifest = targetManifest
}

// WithTillerHost adds the tillerHost to the post tests params
func (o *PostTestsParams) WithTillerHost(tillerHost *string) *PostTestsParams {
	o.SetTillerHost(tillerHost)
	return o
}

// SetTillerHost adds the tillerHost to the post tests params
func (o *PostTestsParams) SetTillerHost(tillerHost *string) {
	o.TillerHost = tillerHost
}

// WithTillerNamespace adds the tillerNamespace to the post tests params
func (o *PostTestsParams) WithTillerNamespace(tillerNamespace *string) *PostTestsParams {
	o.SetTillerNamespace(tillerNamespace)
	return o
}

// SetTillerNamespace adds the tillerNamespace to the post tests params
func (o *PostTestsParams) SetTillerNamespace(tillerNamespace *string) {
	o.TillerNamespace = tillerNamespace
}

// WithTillerPort adds the tillerPort to the post tests params
func (o *PostTestsParams) WithTillerPort(tillerPort *int64) *PostTestsParams {
	o.SetTillerPort(tillerPort)
	return o
}

// SetTillerPort adds the tillerPort to the post tests params
func (o *PostTestsParams) SetTillerPort(tillerPort *int64) {
	o.TillerPort = tillerPort
}

// WriteToRequest writes these params to a swagger request
func (o *PostTestsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XAuthToken != nil {

		// header param X-Auth-Token
		if err := r.SetHeaderParam("X-Auth-Token", *o.XAuthToken); err != nil {
			return err
		}

	}

	if o.RequestBody != nil {
		if err := r.SetBodyParam(o.RequestBody); err != nil {
			return err
		}
	}

	if o.TargetManifest != nil {

		// query param target_manifest
		var qrTargetManifest string
		if o.TargetManifest != nil {
			qrTargetManifest = *o.TargetManifest
		}
		qTargetManifest := qrTargetManifest
		if qTargetManifest != "" {
			if err := r.SetQueryParam("target_manifest", qTargetManifest); err != nil {
				return err
			}
		}

	}

	if o.TillerHost != nil {

		// query param tiller_host
		var qrTillerHost string
		if o.TillerHost != nil {
			qrTillerHost = *o.TillerHost
		}
		qTillerHost := qrTillerHost
		if qTillerHost != "" {
			if err := r.SetQueryParam("tiller_host", qTillerHost); err != nil {
				return err
			}
		}

	}

	if o.TillerNamespace != nil {

		// query param tiller_namespace
		var qrTillerNamespace string
		if o.TillerNamespace != nil {
			qrTillerNamespace = *o.TillerNamespace
		}
		qTillerNamespace := qrTillerNamespace
		if qTillerNamespace != "" {
			if err := r.SetQueryParam("tiller_namespace", qTillerNamespace); err != nil {
				return err
			}
		}

	}

	if o.TillerPort != nil {

		// query param tiller_port
		var qrTillerPort int64
		if o.TillerPort != nil {
			qrTillerPort = *o.TillerPort
		}
		qTillerPort := swag.FormatInt64(qrTillerPort)
		if qTillerPort != "" {
			if err := r.SetQueryParam("tiller_port", qTillerPort); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
